### ISSUE TITLE
Feature request: Enable/disable chime for doorbell

### ISSUE THREAD

**Issue by schumijo** [bropat/ioBroker.eufy-security#100]
First, thank you for this excellent package !

I would like to be able to enable/disable chime for my doorbell as we can do in Eufy Security app.
In app, we have the possibility to enable/disable :

- Existing chime
- Eufy Doorbell chime
- HomeBase as chime
- Alexa as chime

Do you think it is possible to integrate this ?

I will be interesting in making an automation to disable chime when my son is sleeping to only receive notification.

**Comment by bropat** [comment]
Hi @schumijo,

Yes, I think it is possible.

**Comment by bropat** [comment]
To integrate this, I need someone to share a doorbell with me via the Eufy app with admin privileges.

**Comment by bropat** [comment]
@schumijo 

Ready to share?

**Comment by schliemann** [comment]
@bropat I'll gladly mine share it with you. If it is still relevant you can send med the mail you want invited.

**Comment by bropat** [comment]
@schliemann If you have a wired doorbell yes ;)

**Comment by schliemann** [comment]
@bropat I was a bit too quick to offer my doorbell up. Since it is only a battery doorbell and I don't have the eufy chime. But I will try and ask in the homebridge plugin and hear if anyone can help.

**Comment by bropat** [comment]
Brief update:

I have implemented the following chime settings of the battery doorbells in the driver [eufy-security-client](https://github.com/bropat/eufy-security-client):

* Enable/disable indoor chime
* Enable/disable homebase chime
* Set homebase chime ringtone volume
* Set homebase chime ringtone type

**Comment by bropat** [comment]
Released in version 0.6.0
