### ISSUE TITLE
Feature Request: Timestamp Objects

### ISSUE THREAD

**Issue by MizterB** [bropat/ioBroker.eufy-security#102]
Would it be possible to include objects for last_event_timestamp and last_livestream_timestamp?  While I understand these values can be 'burned in' as a watermark, it would be helpful to have these attributes available for use in automations, sensors, etc.

Thank you for the consideration!

**Comment by bropat** [comment]
Hi @MizterB,

every state in ioBroker already has a timestamp, so I think it is better to use this one.
