### ISSUE TITLE
(31897) P2PClientProtocol.lookup(): All address lookup tentatives failed.

### ISSUE THREAD

**Issue by knutbrecht** [bropat/ioBroker.eufy-security#109]
Error in LOG as written in title:

(31897) P2PClientProtocol.lookup(): All address lookup tentatives failed. 

**Versions:**  
 - Adapter version: 0.5.1
 - JS-Controller version: 3.2.16
 - Node version: 14.16.0
 - Operating system: Debian

Is this normal? What does it mean? Wich Adresses are tried to reach?

**Comment by bropat** [comment]
To establish the P2P connection with the Eufy Station, the adapter connects to the Eufy Cloud and asks for the IP address of the station. The adapter receives the response of the local and remote (public) IP addresses from the cloud. If the adapter does not receive a response within 15 seconds, you will receive this error message.

In the last major release, there was some tweaking of the P2P protocol, so it could also be a bug on my part. To understand this I need the debug logs.

**Comment by bropat** [comment]
I found a bug in the eufy-sercurity-client library and fixed it. Try the new version 0.5.2. If you still get this error, I need the debug logs.

**Comment by knutbrecht** [comment]
unfortunately it doesnt solve the problem.
how can I send you the logs?

**Comment by bropat** [comment]
Follow [this](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) howto.
You can find my mail [here](https://github.com/bropat/ioBroker.eufy-security#license).

**Comment by bachoo786** [comment]
@bropat is this resolved ? I get the same error as in the OP and I have a spotlight camera and wired doorbell so no station.
