### ISSUE TITLE
Access to nightvision boolean

### ISSUE THREAD

**Issue by Pongard** [bropat/ioBroker.eufy-security#110]
Hi,

first of, thanks for this excellent adapter!

Would it be possible to add access to the nightvision active value (on or off)? I would like use this in my Smart Home to recognize whether it's dark outside or not. I don't know how Eufy determines whether to switch night vision on or not, but should it be a light detector, access to this raw data would also be very interesting.

Thanks

**Comment by bropat** [comment]
Hi @Pongard,

I am sorry, but this information is not provided anywhere. Thus, I can not provide it either.
