### ISSUE TITLE
getting images from unknown url

### ISSUE THREAD

**Issue by Gilligan2k10** [bropat/ioBroker.eufy-security#111]
**Describe the bug**  
My Eufy-Instance is trying to get images from my homebase ID
**To Reproduce**  
1. direkt after installation

**Expected behavior**  

**Screenshots & Logfiles**  
 Could not download the image within 5 attempts from url: https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2020/11/11/station/T8010N23194910CA/QOl1mK0Y19sh9jXU

**Versions:**  
Version 0.5.2
IOBroker Docker on Synology

**Additional context**

**Comment by bropat** [comment]
Hi @Gilligan2k10,

this is a problem of Eufy, because this URL is pulled from the Eufy cloud. Sometimes this url is no longer valid and thus the adapter can no longer download the image.
