### ISSUE TITLE
Current_mode so richtig?

### ISSUE THREAD

**Issue by kksstefan** [bropat/ioBroker.eufy-security#12]
Hi, ich habe gerade festgestellt, dass der current_mode im Geofence Modus beim nach Hause kommen nur einmal kurz auf "home(1)" geht, danach geht er wieder sofort in "Disarmed(63)". Ist das so gewollt?
Wäre es möglich, einen Datenpunkt zu bekommen, sobald die Kamera eine Aufzeichnung startet? Dann kann man sie  vor der Haustür als Bewegungsmelder nutzen. 

Mit freundlichen Grüßen 

Stefan

**Comment by bropat** [comment]
Hi @kksstefan,

die Information in welchen Status gerade di Station ist, bekomme ich zur Zeit auf 3 Wege (HTTP, P2P und Push Benachrichtigung). Aus irgendeinem Grund bekomme ich über der HTTP-Schnittstelle nicht den gleichen Wert wie von den anderen 2 Schnittstellen. Hier gibt es zur Zeit keine Logik noch meiner Seite, sprich ich setze den `current_mode` state gleich dem Wert den ich gerade von einer Schnittstelle bekomme (wenn ich von mehrere Schnittstellen gleichzeitig Werte bekomme, dann werden diese sequentiell abgearbeitet. Falls dann eine Schnittstelle einen "falschen" Wert liefert und es der letzte abgearbeitete Wert ist, dann haben wir deinen Fall...)

**Comment by kksstefan** [comment]
Hallo Patrick,
danke für dein Update 0.0.5. Ich habe es jetzt mal intensiv  mit dem motion_detected getestet. Der Datenpunkt springt nur auf "wahr", wenn man in der Basissatation die Push-Benachrichtigung an hat. Das bedeutet z.B. als Bewegungsmelder für eine Tür zum Steuern einer Lampe im Heim-Modus nicht zu gebrauchen, weil die Push-Benachrichtigungen aus sind. Oder man nimmt in Kauf, dass das Handy ununterbrochen klingelt. ;-) Danke erstmal für deine Arbeit.
(nur mal zur Info)

Mit freundlichen Grüßen 

Stefan

**Comment by bropat** [comment]
Hallo @kksstefan,

vielen Dank für den ausführlichen Test. Du hast vollkommen Recht, zur Zeit werden hauptsächlich folgende 2 Schnittstellen verwendet:

* HTTP (Web Service; Default alle 10 min.; polling)
* Push-Benachrichtigung (dies setzt voraus dass die Push-Benachrichtigungen in der Eufy-App aktiviert wurden)

Die dritte Schnittstelle ist die komplizierteste (P2P), diese muss erst durch Reverse Engineering "erforscht" werden.
Der Adapter schreibt aber schon alle P2P-Events die er erhaltet im Debug-Log mit. Im konkreten Fall des Bewegungsmelders erwarte ich mir einen Eintrag im Log bezüglich den Befehl `CMD_MOTION_SENSOR_PIR_EVT (1605)`.
Kannst du mir das Debug-Log per Mail zusenden? Damit würdest du mir sehr bei der weiteren Implementation helfen. :)

Danke!

Grüße

**Comment by kksstefan** [comment]
Hi Patrick, 
was mir noch auffällt ist das sich die Datenpunkt nicht von selbst ändert, wenn zum Beispiel die Kamera eine Bewegung erkennt, das passiert nur wenn ich in den Adaptereinstellungen eine Abfragerate von nicht 10min sondern 0.01 Minuten einstelle. Kann man das Automatisch bei Erkennung zum Brocker schicken ?

**Comment by bropat** [comment]
Hallo @kksstefan,
wenn du die Bewegung gleich erhalten möchtest hast du 2 Möglichkeiten:

1. du aktivierst die Push-Benachrichtigung
2. du setzt die "Abtastrate" (wie du bereits gemacht hast) auf einen niedrigen Wert.

Andere Möglichkeiten sind mir zur Zeit nicht bekannt.

Grüße

**Comment by bropat** [comment]
Hallo @kksstefan ,

sollte mit der Version 0.2.0 nun behoben sein.

Grüße
