### ISSUE TITLE
Instanz startet nicht

### ISSUE THREAD

**Issue by st3pp3l** [bropat/ioBroker.eufy-security#120]
Moin,

nach dem ich den Adapter installiere und eine Instanz anlege und diese mit meinen Zugngangsdaten füttere erhalte ich folgenden Log

startInstance system.adapter.eufy-security.0: required adapter "web" not found!
--

Was läuft falsch?

**Comment by bropat** [comment]
Hi,

dieser Adapter braucht zwingend den Web Adapter um zu funktionieren. Einfach den Web Adapter installieren und das Problem ist gelöst.
