### ISSUE TITLE
Never work for me.

### ISSUE THREAD

**Issue by hamdanfadi** [bropat/ioBroker.eufy-security#122]
Hi there,
I have successfully installed ioBroker and installed eufy adapter, I can read my stations and cameras, however I'm getting the attached errors.

Can you please help? 

[Cheers,]([![iobroker](https://user-images.githubusercontent.com/47242007/114977332-9df46c80-9edb-11eb-857a-22f0816d3846.png)]([url](url)))

**Comment by bropat** [comment]
Hi @hamdanfadi,

I don't see any attachment, so I can't understand the error.
