### ISSUE TITLE
Anmeldung schlägt fehl "HTTPApi.authenticate(): Response code not ok"

### ISSUE THREAD

**Issue by knutbrecht** [bropat/ioBroker.eufy-security#123]
Hallo,

habe seit heute Probleme beim Anmelden:
folgende Log-Eintragungen:

![image](https://user-images.githubusercontent.com/60777615/116069058-45676100-a68b-11eb-8cde-7260bbda23ad.png)

Woran kann das liegen?

**Comment by bropat** [comment]
Hallo @knutbrecht,

das liegt an zu vielen fehlgeschlagenen Loginversuchen. Dabei wird der Account für ca. 24h gesperrt. Wie es dazu gekommen ist, kann ich ohne Debug-Logs nicht nachvollziehen.
