### ISSUE TITLE
Meine Floodlight Cam versucht sich permanent bei der Homebas anzumelden

### ISSUE THREAD

**Issue by bsaerdna** [bropat/ioBroker.eufy-security#124]
Hallo bin neu hier, brauch einmal Hilfe,
die Floodlight Cam versucht sich permanent bei der Homebase anzumelden. Prinzipiell nix dagegen nur er schreibt er mir das Log voll. denke auch das es eine Menge Stress im Netzwerk produziert. Ich persönlich brauch das zur zeit nicht kann ich das irgendwo aushalten.

benutze die Version o.5.2

eufy-security.0 | 2021-04-29 21:14:27.650 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 23868.
-- | -- | -- | --
eufy-security.0 | 2021-04-29 21:14:22.252 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:13:09.729 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 22952.
eufy-security.0 | 2021-04-29 21:13:01.014 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:11:46.476 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 29018.
eufy-security.0 | 2021-04-29 21:11:41.229 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:11:37.456 | info | Refresh data from cloud and schedule next refresh.
eufy-security.0 | 2021-04-29 21:10:26.628 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 24848.
eufy-security.0 | 2021-04-29 21:10:20.981 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:09:06.787 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 27933.
eufy-security.0 | 2021-04-29 21:09:01.500 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:07:47.302 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 25311.
eufy-security.0 | 2021-04-29 21:07:40.240 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:06:24.708 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 26718.
eufy-security.0 | 2021-04-29 21:06:19.248 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:04:58.438 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 15488.
eufy-security.0 | 2021-04-29 21:04:52.622 | info | Disconnected from station T8420N30202501B7.
eufy-security.0 | 2021-04-29 21:03:35.446 | info | Connected to station T8420N30202501B7 on host 192.168.178.53 and port 23525.

**Comment by bropat** [comment]
Hallo @bsaerdna,

leider kann man diesen Verbindungsaufbau zur Zeit noch nicht unterbinden. Bis heute hatte ich noch keine Rückmeldung ob die Floodlight Kamera mit meiner Implementierung korrekt funktioniert. Anscheinend nicht 😅.
Da würden mir die Debug-Logs weiterhelfen.
