### ISSUE TITLE
 Feature request: Add support for tilt and pan

### ISSUE THREAD

**Issue by sowoi** [bropat/ioBroker.eufy-security#129]
hello, thanks for the adapter. i use it together with the pan and tilt camera 2k.
everything would be perfect if only the one function was not missing: pan and tilt! 
is it possible to implement this? i will gladly donate a pan and tilt camera if you pass me the amazon wishlist link or know another way i can send it to you. 

ps: i am from germany, but i want others to be able to read this as well, therefore in english and not in german.

**Comment by bropat** [comment]
Hi @sowoi,

it should be feasible, since the commands are transmitted via the P2P interface. Owning the device simplifies the implementation.

Here my [amazon list](https://www.amazon.it/hz/wishlist/ls/14QUPT55W8Y5R?ref_=wl_share)

**Comment by sowoi** [comment]
hi, sorry, i had somewhere in my head that you are german. I ordered the camera and it should arrive on 14 march. if the implementation of the functions is not feasible, it is not the end of the world. i am happy to pay for opensource!

**Comment by bropat** [comment]
Thank you very much, I will get back to you.

PS: I am Italian who speaks German among other languages ;)

**Comment by bropat** [comment]
@sowoi the cam has arrived. this weekend i will try it out.
I will keep you updated.

**Comment by bropat** [comment]
@sowoi 

After a first analysis I can tell you that it is definitely doable. :)

**Comment by sowoi** [comment]
thanks for the update. Have fun with the development.

**Comment by bropat** [comment]
Brief Update:

I am implementing some new features, including the requested ones, in the driver [eufy-security-client](https://github.com/bropat/eufy-security-client). As soon as this is finished I can implement the features in the ioBroker adapter.

**Comment by harryslapalot** [comment]
Any news on pan/tilt support? That would be really awesome! I am just thinking of scripts that move the camera around on a specific path :-)

Thanks for your great work!

**Comment by bropat** [comment]
@harryslapalot 
This functionality has already been implemented in the driver. Will be released soon.

**Comment by bropat** [comment]
@sowoi @harryslapalot Released in version 0.6.0
