### ISSUE TITLE
Feedback and sensors are not working - indoor Cam Pan&Tilt 2K (T8410)

### ISSUE THREAD

**Issue by DivanX10** [bropat/ioBroker.eufy-security#130]
Camera indoor Cam Pan&Tilt 2K (T8410)

**The latest version of eufy-security 0.5.2 is installed. The camera control partially works (listed below what works and what does not work) and the feedback does not work. If I turn it on or off via the mobile app, the value in iobroker will not change from true to false, is this how it should be or should it not be?**

Установлена последняя версия eufy-security 0.5.2. Управление камерой частично работает (ниже перечислил что работает, а что не работает) и не работает обратная связь. Если я через мобильное приложение включу или выключу, то в iobroker не будет меняться значение с true на false, это так и должно быть или так не должно быть?

**Can you add PTZ to control the camera?**
Можете ли добавить PTZ для управления камерой?

**These functions work**
Эти функции работают
Actions:
Enable/disable device
Enable/disable auto night vision
Enable/disable led 
Enable/disable motion detection
Enable/disable pet detection
Enable/disable sound detection
Enable/disable RTSP stream

**These functions do not work, all the time false**
Эти функции не работают, все время false
Events:
Motion detected
Person detected
Crying detected
Sound detected
Pet detected

**Comment by bropat** [comment]
I can't say at the moment. Will look into the matter.

**Comment by bropat** [comment]
@DivanX10 
Now it should work correctly (as described above).

Let me know.

**Comment by DivanX10** [comment]
@bropat  ok, thanks. I will check and be sure to unsubscribe

**Comment by DivanX10** [comment]
I don't have a dog and only checked these Motion\Person\Sound sensors. The sensors work, but one Sound detected sensor for some reason does not transmit false\true messages, while the Motion\Person sensors transmit messages

All sensors work in iobroker
Motion detected-works, the topics have the values false\true
Person detected-works, the topics have the values false\true
Sound detected - does not work, there is no false\true value in topics

In order for the sensors to start working, you need to enable them in the settings
![Screenshot_20210515-025453_EufySecurity](https://user-images.githubusercontent.com/64090632/118341982-11fd5100-b52a-11eb-86ed-9f315fb255b2.jpg)
![Screenshot_20210515-025656_EufySecurity](https://user-images.githubusercontent.com/64090632/118342007-26d9e480-b52a-11eb-9540-ecd4d905ffb9.jpg)

**Comment by DivanX10** [comment]
**Feedback doesn't work or you didn't fix it and only made the sensors work?**
Обратная связь не работает или вы это не исправляли и сделали только работу сенсоров?

**Comment by DivanX10** [comment]
Closing it. Feedback and sensors are working
