### ISSUE TITLE
Cannot GET /eufy-security.0/T8010N2320181105/live/T8113N13202406CC.m3u8

### ISSUE THREAD

**Issue by flonatural** [bropat/ioBroker.eufy-security#132]
Vielleicht steh ich nur auf dem Schlauch, aber ich kann den Livestream nicht öffnen (Bekomme immer die oben abgebildete Meldung).  Bin für jede Hilfe dankbar

**Comment by bropat** [comment]
@flonatural 
Versuche die Instanz und den Adapter zu löschen und installiere den Adapter neu. Manchmal wird das web Plugin des `eufy-security` Adapters vom `web` Adapter nicht geladen.

**Comment by flonatural** [comment]
@bropat 
Danke für den schnellen Tipp. Leider funktioniert das Ganze immer noch nicht. Habe mehrfach die Instanz und den Adapter gelöscht und neu hinzugefügt. Neustart des Systems hat ebenfalls nicht geklappt. Hast du noch einen anderen Tipp?

**Comment by bropat** [comment]
@flonatural 
Ok, super.
Hast du den livestream auch gestartet (unter Objekte findest du unter dem Kamerazweig 2 Schalter `start_stream` und `stop_stream`)?

Achtung: Der Livestream ist noch in einem experimentellen Zustand ;)

**Comment by flonatural** [comment]
@bropat 
Knopf ist gedrückt ;). Manchmal klappt es manchmal nicht, warum das so ist erschließt sich mir noch nicht, aber ich habe Hoffnung das du das in späteren Versionen hinbekommst 👍
