### ISSUE TITLE
Feature Request: Enable light on/off and other settings for Floodlight Cam

### ISSUE THREAD

**Issue by Sascha-U** [bropat/ioBroker.eufy-security#133]
This adapter is great. It would be great if the lights of the device could be switched on or off to use in scripts or via VIS. The eufy app also allows to set brightness for manual, on movement and on schedule. Would be a nice feature to manage that via ioBroker.

**Comment by Sascha-U** [comment]
Is there a way I can help on giving access for testing to you?

**Comment by bropat** [comment]
You have to share the device with me via the menu item "Family & Guests". So that I can test the functions and implement them by reverse engineering, you must share the device with admin rights.

Please share to the following address: patrick.broetto+testing@gmail.com

**Comment by Sascha-U** [comment]
Access has been granted. Please let me know if I should test something.

**Comment by bropat** [comment]
Thank you, have seen. This weekend (or maybe already tonight) I will have a look.
To incorporate the functionality I need to test and record it via the Eufy app. If you agree I'll do it autonomously, if not we can do it together via Discord or Google Meet.

**Comment by Sascha-U** [comment]
Cool, sorry I a was not able to reply earlier. Please go ahead with it. The access  I gave you is a test account and the device is not in use yet. Just let me know when access is no longer needed.

**Comment by bropat** [comment]
Brief Update:

I am implementing some new features, including the requested ones, in the driver [eufy-security-client](https://github.com/bropat/eufy-security-client). As soon as this is finished I can implement the features in the ioBroker adapter.

**Comment by Sascha-U** [comment]
Thanks for the update. I look Forward to test it in IOB.

Sent from Mail for Windows 10

**Comment by bropat** [comment]
@Sascha-U 

Brief Update:

I have implemented almost all Floodlight settings in the driver [eufy-security-client](https://github.com/bropat/eufy-security-client).

**Comment by bropat** [comment]
@Sascha-U Released with version 0.6.0
