### ISSUE TITLE
Last Event Video is not working

### ISSUE THREAD

**Issue by ChristopherGier** [bropat/ioBroker.eufy-security#137]
The Last Event Video Feature is not working for me:

eufy-security.0 | 2021-06-01 12:29:43.014 | error | (4989) Station: T8411P2020000000 command CMD_DOWNLOAD_VIDEO failed with error: ERROR_OPEN_FILE_FAIL (-111)
-- | -- | -- | --
eufy-security.0 | 2021-06-01 12:29:43.013 | debug | (4989) [Station.onCommandResponse] Got p2p command response [{"station":"T8411P2020000000","commandType":1024,"channel":0,"returnCodeName":"ERROR_OPEN_FILE_FAIL","returnCode":-111}]
eufy-security.0 | 2021-06-01 12:29:43.013 | debug | (4989) [P2PClientProtocol.handleData] Station T8411P2020000000 - Result data for command received [{"messageState":{"sequence":18,"command_type":1024,"nested_command_type":1024,"channel":0,"data":{"ty
eufy-security.0 | 2021-06-01 12:29:43.012 | debug | (4989) [P2PClientProtocol.handleData] Station T8411P2020000000 - Received data [{"commandIdName":"CMD_DOWNLOAD_VIDEO","commandId":1024,"resultCodeName":"ERROR_OPEN_FILE_FAIL","resultCode":-111,"messag
eufy-security.0 | 2021-06-01 12:29:43.011 | debug | (4989) [P2PClientProtocol.parseDataMessage] Station T8411P2020000000 - Received data [{"seqNo":18,"header":{"commandId":1024,"bytesToRead":132,"channel":0,"signCode":0,"type":1},"bytesRead":132,"bytes
eufy-security.0 | 2021-06-01 12:29:43.010 | debug | (4989) [P2PClientProtocol.handleMsg] Station T8411P2020000000 - DATA DATA - received from host 192.168.178.77:11311 - Processing sequence 18...
eufy-security.0 | 2021-06-01 12:29:42.999 | debug | (4989) [P2PClientProtocol.handleMsg] Station T8411P2020000000 - ACK DATA - received from host 192.168.178.77:11311 for sequence 18
eufy-security.0 | 2021-06-01 12:29:42.987 | debug | (4989) [P2PClientProtocol._sendCommand] Sending p2p command... [{"station":"T8411P2020000000","sequence":18,"commandType":1024,"channel":0,"retries":0,"messageStatesSize":1}]
eufy-security.0 | 2021-06-01 12:29:42.984 | debug | (4989) [Station.startDownload] P2P connection to station T8411P2020000000 present, download video path: /media/mmcblk0p1/Camera00//media/mmcblk0p1/Camera00/20210601122443.dat.dat

**Comment by bropat** [comment]
@ChristopherGier Please try latest version (0.6.0) and let me know.
