### ISSUE TITLE
Feature Request: Support for T8520 Smart Lock Touch& Wifi

### ISSUE THREAD

**Issue by MouseRatt** [bropat/ioBroker.eufy-security#138]
Hi Bropat, 

First thank you for the excellent adapter! 

I recently purchased a few T8520 smart locks (https://www.bestbuy.com/site/eufy-smart-lock-touch-wi-fi/6425484.p?skuId=6425484 )

Not sure if this lock is easily obtainable outside the US but it is an excellent lock! However, It seems that I can't see the lock state of them in iobroker- not sure if this device can be supported/integrated or not?

Let me know what you think, I'd be more than happy to share a lock with you via the Eufy app w/ admin privileges if you need it. Let me know what email you send admin privileges to if so.

Thanks!

**Comment by bropat** [comment]
Hi @MouseRatt,

you're welcome. It should be possible to support this device. For this I need admin rights on the following account:

patrick.broetto+testing2@gmail.com

**Comment by MouseRatt** [comment]
Awesome thanks so much! I just shared it with you, let me know if you have any trouble getting the invite.

Keep up the great work!

Cheers, MR

**Comment by bropat** [comment]
@MouseRatt 

Have now done some analysis and unfortunately the T8520 device is handled differently than the already implemented T8500, so this means it needs to be fully implemented first. This requires some changes to the driver. To cut a long story short, it will take time.

**Comment by MouseRatt** [comment]
Sounds great, appreciate all the hard work! I'll leave the  lock on an interior door so feel free to lock/unlock at will if you need to for testing.

Cheers

**Comment by bropat** [comment]
@MouseRatt 

I wasn't able to work on it last week, but I still want to give you a status update:

I was able to decrypt all but one last part of the communication. Unfortunately this part was not developed in Java but with an external shared library in C/C++, so the decryption is a lot harder.
But I could already find out that [ECIES](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme) is used as encryption mode.

I have very little time at the moment and so I can't tell you when and if I will be able to do it.

**Comment by bzzlghtyr** [comment]
I'm interested in support for this lock as well. My main need is to be able to read the lock state change from locked/unlocked.

**Comment by thewolf-oz** [comment]
Hi @bropat 

Thanks for referencing this in the issue I raised. I've closed that to consolidate it here. I'm also mainly interested in monitoring lock state and battery, and ideally be able to lock the door (not too fussed on unlock)

Thanks for the great work so far

**Comment by thewolf-oz** [comment]
Hi @bropat 

I appreciate I only just logged this and you've been investigating for a while. After updating Home Assistant today I've been doing some checks and came across this log entry in ioBroker. It appears a certain amount of data is already being pushed but the instance doesn't know what to do with it. Unless of course this is just my action from the Eufy app being detected?

2021-08-05 16:55:47.490 - warn: eufy-security.0 (515) Cus unknown push data: {"name":"Front Door","event_time":1628146547576,"type":51,"station_sn":"T8520<removed_for_privacy>","device_sn":"T8520<removed_for_privacy>","title":"Unlocked - Front Door","content":"Door unlocked by Front Door","push_time":1628146547599,"file_path":"","pic_url":"","push_count":1,"user_id":"<removed_for_privacy>","short_user_id":"0000","storage_type":1}

**Comment by bropat** [comment]
Short update:

Unfortunately, I've been busy the last few weeks and so couldn't work on it.
The encryption method used is ECIES (AES-CBC 128, HMAC_SHA_256_256, KDF: HKDF SHA256 - RFC 5869).

**Comment by MouseRatt** [comment]
Hi Bropat,

Any hope for support for this or doesn't look likely? Noticed some activity in my test device so got my hopes up :)

Thanks for all your hard work!

**Comment by bropat** [comment]
@MouseRatt 

Good news: I was able to decrypt the communication (a few seconds ago ;) ). I can now close and open the lock.
I still have to decipher and implement a few small things so that everything runs smoothly, but the hardest part is now behind me.
In the next few days I will publish the new version with support for the device.

**Comment by bropat** [comment]
Thanks for sharing and for your patience ;)

PS: I will let you know as soon as I no longer need the sharing.

**Comment by MouseRatt** [comment]
Wow, amazing! Bravo Bropat!!!!

Take as long as you need, that's what The device was bought for -- testing, so take as long as you need and I will repurpose it after you are finished.

Best,

MR￼

**Comment by bropat** [comment]
@MouseRatt 

Can you please check the lock as I can't reach it anymore.

![image](https://user-images.githubusercontent.com/2305255/148760011-d1ed6ffc-346b-4804-8a37-bb63c4fd24dd.png)

**Comment by MouseRatt** [comment]
Weird- not sure - it seems it got dropped from my network somehow. Had to reboot the lock. 

Don't think it had anything to do with your testing, but let me know if it happens again.

**Comment by bropat** [comment]
@MouseRatt 

Today the lock is offline :(

![image](https://user-images.githubusercontent.com/2305255/149169292-998133ac-fb69-46dc-940a-9e226facbefe.png)

Can you look at it?

Thx!

**Comment by MouseRatt** [comment]
Try now should be up not sure why they are acting up... I have 6 of them and they all went offline last night

**Comment by thewolf-oz** [comment]
> > I'm interested in support for this lock as well. My main need is to be able to read the lock state change from locked/unlocked.
> 
> i'm not meaning to sidetrack the progress here and I also want to preface this with a statement that I don't know what's causing this issue, but I noticed recent activity here so that's why I'm coming here with it.
> 
> I've noticed battery issues and an inability to access my lock through the app, as well as inability to lock/unlock from the app. I tried re-configuring the lock and disabling the iobroker add-on and I am still unable to control the lock in my app. I had Eufy send me a replacement battery and it drained even more quickly as well.
> 
> again, i'm really looking to see if anything involved here or with the integration may have caused this and if it's something I can reverse, but I don't know that it's being caused by this integration.

I think a recent firmware update mentioned both battery and device dropping offline

**Comment by kunwarsethi** [comment]
I have the same lock: T8520, I contacted Eufy and the Offline issue is firmware based. According to them, the lock has issues connecting to a WiFi 6 capable router. My lock disconnects between 6-24 hours after resetting the device and WiFi.

**Comment by kunwarsethi** [comment]
> I have the same lock: T8520, I contacted Eufy and the Offline issue is firmware based. According to them, the lock has issues connecting to a WiFi 6 capable router. My lock disconnects between 6-24 hours after resetting the device and WiFi.

I set up an ESP8266 as a NAT Router to see if the issue really is with my WiFi 6 router and the T8520 was able to stay connected to it for about 36 hours before going offline. It seems like the offline issue is a huge flaw in their firmware which almost all the T8520 owners are complaining about.

**Comment by bropat** [comment]
@MouseRatt

Can you please check the lock as I can't reach it anymore.

Thanks!

**Comment by MouseRatt** [comment]
Should be accessible now - low battery before

**Comment by MouseRatt** [comment]
@bropat 

Should be accessible now was low battery

**Comment by bropat** [comment]
@MouseRatt 

Offline again :(

**Comment by MouseRatt** [comment]
@bropat 

should be back up now, seems like it is having some issue waking from sleep/low power state since last firmware update. Toggling the deadbolt manually reconnects it...

**Comment by bropat** [comment]
@MouseRatt 

Ok, thanks a lot! It doesn't look very stable ;)

In the meantime, I have successfully tested all P2P functions. Now I still have to check the push notifications (you will get them also in the process :P).

With this device, there is another communication interface via the MQTT protocol (only for notification of changes). However, I will not integrate this at the moment.

**Comment by MouseRatt** [comment]
@bropat 

Amazing work! Sounds great!! Mqtt support would be awesome in the future.

Yes, unfortunately stability has been an issue as of late. It could honestly also be my network as well (midway through overhaul and upgrade to Wifi 6 capable APs which has known issues with current FW) It's honestly hard to troubleshoot as well because the Eufy app shows them "online" until I try to access/toggle them.

**Comment by bropat** [comment]
@MouseRatt 

The implementation is done.
I have also implemented the MQTT interface of the lock, so you also get the status change whether the lock is open or closed even with deactivated push notifications and no P2P connection ;)

**Comment by bropat** [comment]
New version (0.8.0) released that supports the lock

**Comment by kunwarsethi** [comment]
> @MouseRatt
> 
> The implementation is done. I have also implemented the MQTT interface of the lock, so you also get the status change whether the lock is open or closed even with deactivated push notifications and no P2P connection ;)
> 
> It was a long journey, but now it's done ;)

Awesome!! Thank you so much! I can't wait for this to be implemented in the Homebridge version.

**Comment by MouseRatt** [comment]
Wow Bravo!!! Great work @bropat!
