### ISSUE TITLE
Fehler bei Livestreams

### ISSUE THREAD

**Issue by TobiasF1986** [bropat/ioBroker.eufy-security#141]
Hallo,
leider erhalte ich mit meiner Eufy 2c immer wieder Probleme bei allem was die Verarbeitung der Livestreams geht. Alles andere klappt scheinbar sehr gut. 

![eufy_1](https://user-images.githubusercontent.com/45529372/122668879-8b87ff00-d1ba-11eb-86d2-8ba0c00a51ab.png)
![eufy_2](https://user-images.githubusercontent.com/45529372/122668880-8c209580-d1ba-11eb-9889-3d3c8e01ba7a.png)

**Comment by bropat** [comment]
@bropat 

Bitte den Adapter im [Debug-Modus](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) versetzen und mir die Debug-Logs [zusenden](https://github.com/bropat/ioBroker.eufy-security#license).
