### ISSUE TITLE
Klingelknopf über Datenpunkt triggern

### ISSUE THREAD

**Issue by nicomania** [bropat/ioBroker.eufy-security#145]
Hallo, 
erst einmal vielen Dank für das tolle Plugin! Bei meinen ersten Tests laufen alle features mit meiner T8200 Türklingel (wired 2k doorbell) wunderbar und ohne Verzögerung.
Ich hätte jedoch eine Bitte: Ist es möglich einen Datenpunkt anzulegen, den ich über ein Skript triggern kann und im Anschluss meine EUFY App ausgelöst wird, als hätte jemand geklingelt? Also wie der Klingelknopf an der EUFY Hardware, jedoch als Datenpunkt. 
Ich benutze die EUFY Türklingel nämlich nur als Kamera und habe einen schönen klassischen Klingelknopf. Dieser Knopf ist bereits in iobroker integriert. Ich könnte dann mit einem Skript die EUFY Klingel auslösen und über die App mit dem Besucher sprechen.
Vielen Dank im Voraus!

**Comment by bropat** [comment]
@nicomania 

> Ist es möglich einen Datenpunkt anzulegen, den ich über ein Skript triggern kann und im Anschluss meine EUFY App ausgelöst wird, als hätte jemand geklingelt?

Laut meinem Wissensstand ist es nicht möglich den Klingelknopf der Eufy Doorbell softwaretechnisch auszulösen.

**Comment by nicomania** [comment]
ok, schade, danke.
