### ISSUE TITLE
Push Benachrichtigungen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by moyo77** [bropat/ioBroker.eufy-security#15]
Bei den Cameras sind zahlreiche Datenpunkte hinzugekommen, allerdings kann ich seit der Version 0.0.5 ich die Push-Benachrichtigungen bei den Objekten nicht mehr finden. Ist das so gewollt? Push connection ist aktiviert.
Die Funktion war ganz hilfreich, da man sich den Inhalt direkt z.B. im VIS anzeigen lassen konnte.

**Comment by linuxq** [comment]
Hallo,
wie kann ich Snapshots in der Visu darstellen? Ich würde gerne das aktuellste Snapshot der Doorbell darstellen. Wenn ich den Punkt in dem dir URL liegt als Quelle für ein Image nehme, wird das kurz angezeigt, aber bei Refresh verschwindet es. Danke für Tipps.

**Comment by bropat** [comment]
Hi @moyo77,

ja die Push-Benachrichtigung wurde im Adapter integriert und wird für die Events benötigt (movement detection, person detection etc.).
Die Datenpunkte für die Push-Benachrichtigung wurden deshalb entfernt (wurden nur provisorisch publiziert um ein einfacheres Debugging zu ermöglichen).

**Comment by bropat** [comment]
Hi @linuxq,

diese Funktionalität wird in einer der nächsten Versionen implementiert (kannst gern eine Issue als Feature-Request öffnen).
Bitte jegliche Fragen im ioBroker Forum ([hier](https://forum.iobroker.net/topic/39276/neuer-adapter-eufy-security)) stellen und nicht als GitHub issue.
