### ISSUE TITLE
Error: HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by Bjoern2006** [bropat/ioBroker.eufy-security#154]
Seit heute morgen bekomme folgende Fehlermeldungen im Log:

**"ring.0 (XXXX) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device instance in method getDevices(). HTTPError: Response code 404 (Not Found)"**

Weiß jemand was das sein kann?
Am System wurde nichts geändert...

Versionen:
Node.js: v12.22.1
NPM: 7.19.1
Adapter: 1.2.2

**Comment by bropat** [comment]
@Bjoern2006 
Ja ein anderer Adapter "ring".

**Comment by Bjoern2006** [comment]
> @Bjoern2006 
> Ja ein anderer Adapter "ring".

Es gibt einen weiteren?
Ich hab unter Adapter den Ring ausgewählt und dann auf das Fragezeichen geklickt...

**Comment by bropat** [comment]
Du hast eine issue auf den Adapter eufy-security aufgemacht für den Adapter ring...

**Comment by Bjoern2006** [comment]
> Du hast eine issue auf den Adapter eufy-security aufgemacht für den Adapter ring...

Sorry! Muss mich da irgendwie verklickt haben. Danke trotzdem!
