### ISSUE TITLE
Error Message after camera recognized motion

### ISSUE THREAD

**Issue by morskipas** [bropat/ioBroker.eufy-security#157]
**Describe the bug**  
The installation of the adapter is complete and everything is fine.
But, when the camera detect a motion I get this error.

**To Reproduce**  
1. Insatll adapter
2. Configute it
3. Go to test camera (eufyCam 2 (T8114)) to test it

**Expected behavior**  
No error message.

**Screenshots & Logfiles**  

`2021-08-15 12:30:56.418  - [32minfo[39m: eufy-security.0 (12904) Downloading video event for device xxxxxxxx in 18.979 seconds...
2021-08-15 12:32:29.481  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage(): An error occurred: ffmpeg exited with code 1: Output #0, image2, to '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.jpeg':
Output file #0 does not contain any stream

2021-08-15 12:32:29.483  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage(): ffmpeg output:

2021-08-15 12:32:29.483  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage(): ffmpeg stderr:
ffmpeg version 4.4-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 0x43a5620] Skip ('#EXT-X-VERSION:3')
[hls @ 0x43a5620] Cannot get correct #EXTINF value of segment /opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.ts, set to default value to 1ms.
[hls @ 0x43a5620] Opening '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.ts' for reading
[aac @ 0x43b12b0] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x43b12b0] channel element 3.15 is not allocated
[aac @ 0x43b12b0] Multiple frames in a packet.
[aac @ 0x43b12b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x43b12b0] Inconsistent channel configuration.
[aac @ 0x43b12b0] get_buffer() failed
[aac @ 0x43b12b0] Number of bands (3) exceeds limit (1).
[aac @ 0x43b12b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x43b12b0] Inconsistent channel configuration.
[aac @ 0x43b12b0] get_buffer() failed
[aac @ 0x43b12b0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x43b12b0] channel element 2.13 is not allocated
[aac @ 0x43b12b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x43b12b0] Inconsistent channel configuration.
[aac @ 0x43b12b0] get_buffer() failed
[aac @ 0x43b12b0] Number of bands (29) exceeds limit (20).
[aac @ 0x43b12b0] Number of bands (51) exceeds limit (43).
[aac @ 0x43b12b0] Number of bands (7) exceeds limit (2).
[aac @ 0x43b12b0] channel element 2.0 is not allocated
[aac @ 0x43b12b0] channel element 3.5 is not allocated
[aac @ 0x43b12b0] channel element 1.0 is not allocated
[hls @ 0x43a5620] decoding for stream 1 failed
[hls @ 0x43a5620] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[hls @ 0x43a5620] Could not find codec parameters for stream 1 (Audio: aac (Main) ([15][0][0][0] / 0x000F), 5.1, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, hls, from '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.m3u8':
  Duration: 00:00:00.00, start: 1.400000, bitrate: 1232 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (Main) ([15][0][0][0] / 0x000F), 5.1, fltp
    Metadata:
      variant_bitrate : 0
Output #0, image2, to '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.jpeg':
Output file #0 does not contain any stream

2021-08-15 12:32:29.484  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage - station: xxxxxxxx device: xxxxxxxx - Error [{}]
2021-08-15 12:34:23.746  - [32minfo[39m: eufy-security.0 (12904) Downloading video event for device xxxxxxxx in 19.092 seconds...
2021-08-15 12:42:29.820  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage(): An error occurred: ffmpeg exited with code 1: Output #0, image2, to '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.jpeg':
Output file #0 does not contain any stream

2021-08-15 12:42:29.822  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage(): ffmpeg output:

2021-08-15 12:42:29.823  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage(): ffmpeg stderr:
ffmpeg version 4.4-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 0x2cfa620] Skip ('#EXT-X-VERSION:3')
[hls @ 0x2cfa620] Cannot get correct #EXTINF value of segment /opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.ts, set to default value to 1ms.
[hls @ 0x2cfa620] Opening '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.ts' for reading
[aac @ 0x2d062b0] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x2d062b0] Multiple frames in a packet.
[aac @ 0x2d062b0] Number of bands (24) exceeds limit (12).
[aac @ 0x2d062b0] channel element 1.1 is not allocated
[aac @ 0x2d062b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x2d062b0] Inconsistent channel configuration.
[aac @ 0x2d062b0] get_buffer() failed
[aac @ 0x2d062b0] channel element 1.0 is not allocated
[aac @ 0x2d062b0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x2d062b0] channel element 3.12 is not allocated
[aac @ 0x2d062b0] SBR was found before the first channel element.
[aac @ 0x2d062b0] Number of bands (38) exceeds limit (30).
[aac @ 0x2d062b0] Dependent coupling is not supported together with LTP
    Last message repeated 17 times
[aac @ 0x2d062b0] channel element 3.6 is not allocated
[aac @ 0x2d062b0] channel element 2.9 is not allocated
[aac @ 0x2d062b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x2d062b0] Inconsistent channel configuration.
[aac @ 0x2d062b0] get_buffer() failed
[aac @ 0x2d062b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x2d062b0] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x2d062b0] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x2d062b0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x2d062b0] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x2d062b0] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x2d062b0] channel element 1.9 is not allocated
[hls @ 0x2cfa620] decoding for stream 1 failed
[hls @ 0x2cfa620] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[hls @ 0x2cfa620] Could not find codec parameters for stream 1 (Audio: aac (Main) ([15][0][0][0] / 0x000F), 3.0, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, hls, from '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.m3u8':
  Duration: 00:00:00.00, start: 1.400000, bitrate: 1232 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (Main) ([15][0][0][0] / 0x000F), 3.0, fltp
    Metadata:
      variant_bitrate : 0
Output #0, image2, to '/opt/iobroker/iobroker-data/eufy-security.0/xxxxxxxx/last_event/xxxxxxxx.jpeg':
Output file #0 does not contain any stream

2021-08-15 12:42:29.823  - [31merror[39m: eufy-security.0 (12904) ffmpegPreviewImage - station: xxxxxxxx device: xxxxxxxx - Error [{}]`

****Versions:****  
 - Adapter version: <0.6.0>
 - JS-Controller version: <3.3.15>
 - Node version: <14.17.5>
 - Operating system: <raspbian 10>

**Comment by bropat** [comment]
Please set the adapter in [debug mode](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) and then send me the logs by mail.
You can find the mail address [here](https://github.com/bropat/ioBroker.eufy-security#license).
