### ISSUE TITLE
Station > guard_mode Value is not accepted

### ISSUE THREAD

**Issue by Catwatch** [bropat/ioBroker.eufy-security#159]
When changing the value manually, this is not confirmed by the iobroker. The status of the station remains unchanged.
![Image 1](https://user-images.githubusercontent.com/38084979/130016057-699b57c4-37ab-4e6c-8ac5-8749a1ea96b3.png)

**Comment by bropat** [comment]
@Catwatch Try version 0.6.1 released a few seconds ago.

**Comment by Catwatch** [comment]
> 
> 
> @Catwatch Try version 0.6.1 released a few seconds ago.

Works fine- THX!
