### ISSUE TITLE
Guard-mode wechselt nicht

### ISSUE THREAD

**Issue by tofrie** [bropat/ioBroker.eufy-security#16]
Hallo,

Leider funktioniert es nach der Aktualisierung immer noch nicht. Ich habe ein Update auf die aktuelle version gemacht. Bei mir möchte ich den Status in Abhängigkeit meiner Alarmanlage wechseln. Mit meinem Workaround (Adapter Neustarten) klappt es.

**Comment by bropat** [comment]
Hallo @tofrie ,

bei mir funktioniert es einwandfrei. Kannst du mir bitte die Logs zusenden?

**Comment by bropat** [comment]
@tofrie Kann es vielleicht sein, dass es nach einiger Zeit nicht mehr geht? Sprich wenn du nun die Alarmanlage scharf schaltest 
 und nachher wieder unscharf, sollte der Modus auch bei der Eufy-Station korrekt wechseln.
Das Problem könnte sein, dass der Adapter nach einiger Zeit die Verbindung mit der Eufy-Station verliert und dies nicht mitbekommt und denkt er sei immer noch verbunden (die Verbindung ist ja stateless - UDP).

**Comment by tofrie** [comment]
Damit ich dir logs schicken kann muss der Debugmodus aktiv sein oder? Ich würde mich am Wochenende noch einmal dran setzen. Das Skript funktioniert eigentlich ganz einfach. Wird die Alarmanlage scharf geschaltet, wird eufy auf abwesend geschaltet und das ganze umgekehrt.

**Comment by bropat** [comment]
Ja. Mittlerweile habe ich die Ursache gefunden. Gebe dir hier Bescheid sobald auch dieser Bug behoben wurde.

**Comment by bropat** [comment]
@tofrie Habe gerade die neue Version (0.0.8) publiziert. Kannst du einen Test fahren und mir Bescheid geben? :)

Danke!

**Comment by tofrie** [comment]
Ich habe es ein paar mal getestet. Bis jetzt funktioniert es. Ich würde dir morgen ein finales Feedback geben. Vielen Dank schon einmal 👍

**Comment by tofrie** [comment]
Es lief heute ohne Probleme. Es scheint der Fehler ist gelöst. Super Arbeit!
