### ISSUE TITLE
2K Video-Türklingel Wert Ringing ändert sich nicht

### ISSUE THREAD

**Issue by tofrie** [bropat/ioBroker.eufy-security#161]
Ich würde den Wert Ringing gern nutzen um ein Telefon anzusteuern. Leider ändert sich dieser nicht auf True wenn an der Hastür geklingelt wird.

**Comment by bropat** [comment]
@tofrie Hast du folgende Einstellung der Türklingel aktiv?

![image](https://user-images.githubusercontent.com/2305255/130261192-b1f7caac-b037-4b2d-84e9-44d444649a83.png)

**Comment by tofrie** [comment]
Problem gelöst. Der Fehler steckt im Detail 🧐 vielen Dank!
