### ISSUE TITLE
indoor Cam Pan&Tilt 2K (T8410) Guard Mode

### ISSUE THREAD

**Issue by FeromonDE** [bropat/ioBroker.eufy-security#162]
**Describe the bug**  
Nach dem Update auf 0.6.2 kein Guard Mode State mehr für indoor Cam Pan&Tilt 2K.

**Comment by bropat** [comment]
@FeromonDE Kannst du den Adapter nochmals neu starten und nachsehen ob der State wieder auftaucht?

**Comment by FeromonDE** [comment]
> 
> 
> @FeromonDE Kannst du den Adapter nochmals neu starten und nachsehen ob der State wieder auftaucht?

Habe ich schon versucht, auch alles gelöscht und neu gestartet

**Comment by bropat** [comment]
Dann benötige ich die debug Logs des Adapters. Kannst du mir diese per Mail senden?

**Comment by FeromonDE** [comment]
> 
> 
> Dann benötige ich die debug Logs des Adapters. Kannst du mir diese per Mail senden?

Ja kann ich, wenn wieder am PC bin.

**Comment by bropat** [comment]
Im Log finde ich nichts seltsames. Kannst du mir bitte noch ein Screenshot der eufy-security States in der Objekt Ansicht senden.
Fehlt ausschließlich der `guard_mode` State?

**Comment by FeromonDE** [comment]
Mit freundlichen Grüßen
Dmitrij Geller


вт, 24 авг. 2021 г. в 20:56, bropat ***@***.***>:
