### ISSUE TITLE
Thanks for the excellent integration

### ISSUE THREAD

**Issue by DivanX10** [bropat/ioBroker.eufy-security#164]
Dear bropat. I express my great gratitude to you for the excellent integration. You can't imagine what emotional joy 😁 I experienced today when I discovered that an update has been released and my camera has already been added to it: Hijacking Indoor Cam 2K Pan & Tilt T8410. Unfortunately, there is no other topic here besides God, and I created a topic for gratitude in the bug. I apologize.

I made a manual on how to implement everything
https://community.home-assistant.io/t/eufy-camera-integration/121758/1392?u=divanx10

**Comment by bropat** [comment]
@DivanX10 Thank you so much!
