### ISSUE TITLE
Passwort Eingabe Feld

### ISSUE THREAD

**Issue by Trunks1982** [bropat/ioBroker.eufy-security#168]
Hi hab gerade mal den neuen Adapter installiert und jedesmal wenn ich Passwort eingeben will entfernt sich das Eingabefeld.Also Nutzung für mich nicht möglich.

**Comment by nukleuz80** [comment]
Hi, kopiere einfach dein PW in die Zwischenablage und füge es in das PW-Feld ein und speicher ab - Feld geht zwar weg aber er nimmt es….

**Comment by nukleuz80** [comment]
https://github.com/bropat/ioBroker.eufy-security/issues/163

Hatte ich schon geschrieben 2 Issues weiter unten.

**Comment by Trunks1982** [comment]
Ok.Hatte es nicht gesehen.Muss aber dazu schreiben das es bei mir nur im Chrome Browser funktioniert hat.Safari ging es nicht.
