### ISSUE TITLE
Roadmap discussion: MQTT

### ISSUE THREAD

**Issue by fuatakgun** [bropat/ioBroker.eufy-security#174]
Hey @bropat as you are aware i am busy with integration of home assistant with eufy-security-ws and this codebase is an integration point for iobroker.

Guven that you have a solid docker wrapper for eufy-client, should we merge into one docker solution and use mqtt discovery option? 

So, we could have one docker solution which communicates with MQTT brokers of isolated system (iobroker or home assistant) and we could have get benefits of sharing code base.

Please let me know what you think, i am fine to have a live discussion on this. We can meet virtually.

Idea is based on this discussion: https://community.home-assistant.io/t/why-home-assistant-doesnt-have-an-external-api-for-integrations/307478

**Comment by bropat** [comment]
I understand your suggestion, but I don't want to invest time in it.
I am sorry.
