### ISSUE TITLE
Enable flag on T8420 cameras are inverted

### ISSUE THREAD

**Issue by calielc** [bropat/ioBroker.eufy-security#178]
I have a T8420 camera (Floodlight Cam) and when I toggle the enabled flag is make the opposite behavior, mean:
- state False is turning on the camera
- state True is turning off the camera

**To Reproduce**  
1. Toggle the enabled flag

**Expected behavior**  
- state **False** is turning **OFF** the camera
- state **True** is turning **on** the camera

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/2756159/138589974-91111d66-c911-4d59-a664-1a45a277cbeb.png)
![image](https://user-images.githubusercontent.com/2756159/138590237-899c1a5f-4435-4479-a02e-87cd61bfc065.png)

![image](https://user-images.githubusercontent.com/2756159/138589962-c045f7cf-b9f2-46a1-98b4-3444a1611618.png)
![image](https://user-images.githubusercontent.com/2756159/138590251-3495c491-69ba-4254-894d-4c14a18a2ff2.png)
**Versions:**  
 - Adapter version: 0.7.1
 - Node version: V12.21.0

**Comment by bropat** [comment]
@calielc 

To fix this, I need access to a device.

Could you share your device with me on one of the following accounts:

* patrick.broetto+eu1@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Let me know.

**Comment by bropat** [comment]
@calielc 

Can you give me access?

**Comment by calielc** [comment]
Hi @bropat 
Thanks for taking care of the plugin.
Definitely, I would like to help you but due to privacy concerns, I would be able to give you access to my camera.

Is there any other way to help?

**Comment by bropat** [comment]
@calielc 

No problem, in the meantime someone else was kind enough to make his device available and so this device will also be fully integrated in the next release.
Long story short, the problem has already been fixed in the code.
