### ISSUE TITLE
HomeAssistant integration?

### ISSUE THREAD

**Issue by air720boarder** [bropat/ioBroker.eufy-security#18]
Is there an opportunity for Home Assistant integration? There are other projects but none that appear to have the flexibility/capability this one does.

**Comment by calielc** [comment]
I'm looking forward for it too

**Comment by calielc** [comment]
I'm looking forward for it tool

**Comment by bropat** [comment]
@air720boarder @calielc I'm sorry, but unfortunately not. My main focus is on ioBroker.

Why not switch to ioBroker? ;)
