### ISSUE TITLE
Floodlight Cam 2 pro Unterstützung geplant?

### ISSUE THREAD

**Issue by rumpeltec** [bropat/ioBroker.eufy-security#183]
Hallo Bropat,

die Floodlight Cam 2 pro (Modell T8423) wird nicht im IoB erkannt. 
Die Kamera arbeitet leider nur direkt über WLAN,. Homebase Integration soll laut Eufy in Q3 / Q4 kommen.
Ist eine interessante Kamera, da 230V festverdrahtet und würde sich bestimmt prima in VIS machen.

Vielen Dank an dieser Stelle für deine hervorragende Arbeit.

**Comment by bropat** [comment]
Hallo @rumpeltec,

was funktioniert nicht?
Das Gerät sollte eigentlich erkannt werden auch wenn es gezielt nie getestet wurde. Was ich mir eher erwarte ist, dass manche Befehle nicht korrekt funktionieren oder manche Attribute falsch ausgewertet werden, aber nicht das das Gerät nicht "erkannt" wird.

Hast du im Adapter ein Eufy-Account mit Admin-Rechte konfiguriert?

Falls ich dieses Gerät besser unterstützen soll, brauch ich entweder Zugang zum Gerät (durch Freigabe in der App) oder das Gerät selbst.

**Comment by rumpeltec** [comment]
Hallo @bropat ,
vielen lieben Dank für den Hinweis mit dem Account.
Habe jetzt im Adapter den Account gewechselt und voila ...  die Floodlight Cam ist da.
Alle Datenpunkte wurden angelegt.

Ich werde dann mal in Ruhe alles durchtesten.

und nochmals herzlichen Dank für deine Arbeit mit dem Adapter.
