### ISSUE TITLE
Version 0.7.1

### ISSUE THREAD

**Issue by Trunks1982** [bropat/ioBroker.eufy-security#186]
hi,
ich hab von 0.7.0 auf 0.7.1 ein Update gemacht und seid dem sagt mir das IoBorker Protokoll es würden Module fehlen.
Die alte Version hat funktioniert, kann es sein das bei der neuen Version irgendwas schilfgelaufen ist?

Gruß Christoph

**Comment by bropat** [comment]
Ohne Log bzw. Fehlermeldungen kann ich dir leider nicht behilflich sein.

**Comment by bropat** [comment]
Laut deiner anderen issue #185 tippe ich auf ein falsch durchgeführtes Upgrade des Adapters.

Zur Info: Der Adapter heißt **ioBroker.eufy-security**.

**Comment by Trunks1982** [comment]
> Laut deiner anderen issue #185 tippe ich auf ein falsch durchgeführtes Upgrade des Adapters.
> 
> Zur Info: Der Adapter heißt **ioBroker.eufy-security**.

Kann nicht sein hab sogar alles deinstalliert und wieder neu installiert.
![Bild 12 11 21 um 13 21](https://user-images.githubusercontent.com/62701386/141466427-27dc7601-b23e-46ad-aa9b-f5b2f28f6bc5.jpg)

**Comment by bropat** [comment]
@Trunks1982 

Dies ist ein Installationsfehler deinerseits. Ich kann dir garantieren, dass wenn alles korrekt installiert wird, die Version 0.7.1 einwandfrei funktioniert.

**Comment by Trunks1982** [comment]
Mehr als die Adresse vom GitHub kopieren und unter Katze Benutzerdefiniert einfügen muss man ja nicht.Bei anderen Adaptern funktioniert diese Methode.

**Comment by Trunks1982** [comment]
Jetzt gerade nochmal alles deinstalliert und wieder neu installiert genau die gleichen Fehler.

**Comment by bropat** [comment]
Schreib mal hier wie du alles neu installierst, Schritt für Schritt, dann kann ich dir sagen wo genau der Fehler liegt.

**Comment by Trunks1982** [comment]
> Schreib mal hier wie du alles neu installierst, Schritt für Schritt, dann kann ich dir sagen wo genau der Fehler liegt.



Ich kopiere von der ersten Seite hier vom Adapter den Link und fürge in über die Katze benutzerdefiniert den link ein und er installiert ihn dann auch.Sehe da auch keine Errors in der debug ausgabe.

**Comment by bropat** [comment]
So kann ich dir leider nicht helfen.

**Comment by Trunks1982** [comment]
> So kann ich dir leider nicht helfen.

Versteh ich jetzt nicht.Hab doch oben erklärt.

**Comment by Trunks1982** [comment]
![Bild 13 11 21 um 09 59](https://user-images.githubusercontent.com/62701386/141612807-df2c13aa-d8c4-4621-91b4-7bcf10275f14.jpg)

So wie im Text beschrieben

**Comment by Trunks1982** [comment]
Alles nochmal mehrmals ausprobiert IO auf dem neusten Stand.Installation über Katze klappt ja, aber sobald ich eine Instanz erstellt habe und die Verbindung herstellen will kommen immer wie oben auf dem Bild zusehen die Fehlermeldung.Adapter ist so nicht zugbrauchen.

**Comment by Trunks1982** [comment]
Kann es vielleicht an nodejs Version liegen?

**Comment by Trunks1982** [comment]
Ok.Habs jetzt über Nachinstallation von npm i in der console zum laufen gebracht.
