### ISSUE TITLE
Refresh of state "motion detected"

### ISSUE THREAD

**Issue by reddddich** [bropat/ioBroker.eufy-security#189]
Great work so far!
I have one concern regarding the state of motion detected. I wanted to use it as a trigger to control lights. After coding a while I recognized that the "motion detected" state changes differ from the push notifications I get from homekit. 
"Motion detected" state: Stays ~10sec on true
Next possible "motion detected" state: >2min

Is there any possibility to change the refresh loops?

**Comment by bropat** [comment]
"Motion detected" is set to true when receiving a push notification from Eufy. In order for this to work, you must of course have this functionality enabled in the Eufy app.

I can't help you with homekit as I don't use it.

**Comment by reddddich** [comment]
Everything is enabled and I am receiving the states in iobroker => "eufy-security.0.xxx.cameras.xxx.motion_detection = true" 
Again my issue/question:
If I get a  "eufy-security.0.xxx.cameras.x.motion_detected = true" it will stay ~ 10 seconds, then switch to "false".
If now a motion is detected by the camera (camera status led switch to red), **no state change is received in iobroker** (but in Homekit) for more than 2 minutes.
My question is if there is any possibility to reduce these 2 minutes until it is possible to get a state change published in iobroker.

**Comment by bropat** [comment]
As already mentioned, this status is directly determined by the push notifications received from the Eufy Cloud. There is no "refresh" on my side.

So the answer is no.
