### ISSUE TITLE
Gerät nicht verbunden

### ISSUE THREAD

**Issue by SPITZGITHUB** [bropat/ioBroker.eufy-security#197]
Hallo,

habe den Adapter installiert, Cloud aktiviert aber leider verbindet sich der Adapter nicht mit dem Gerät in der cloud.
Ich habe eine Wired Doorbell 2k (T8200). Im Protokoll erscheint (Text hinter Captcha gekürzt!):

eufy-security.0 | 2021-11-24 18:26:40.507 | warn | Captcha:  <img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAYAAAAJ3cTrAAAI5klEQVR4nOxaf3AU5Rl+CCRgCIiCLfLDLEqTAuvFHkVhuw5ui6hMPaatg9axyrY9O+1gBit1xmktZcQRpRUbtdRJpwsdLBmx1t6AVLQs0mVFxCtctpFQK0ssSTQakQCGBNzOe3mX2exs7lfu0v5xz8zN5vv2+/F+zz77vu/3bUoAoOfdww79UEReMMJbcIktu7xq2FBMLqoSzT8dQBWALwKoBvAFrmsHELU0862hsCWfSJKXSqX5IFhUpTIAMwBcCWAW/00EXkHTAzjk+TUBmAOgAsAEAGsszTw4WBuGEv0IKwS5oipFATwNoNNDWpNLouM4x/654XXH1+cqIhPAXQAaLM1Ucpn7f4V+r79LXBC53rosCaZ+z1iaeU8mjWctnUdjfwpgJl/FLOb6v8CIoEovaakIzpDc3QCWpWskqhKp8jYA8wBcyNU6gDEZzJEXNNdGRwKYD+DzAHZV19W/l8s4GSsuXXaQimBRlci4RZZmNoqqN............... 

eufy-security.0 | 2021-11-24 18:26:40.506 | warn | Captcha authentication request received, please enter valid captcha in state eufy-security.0.captcha

Wie bekommen ich die Verbindung zum Gerät

Grüsse

**Comment by bropat** [comment]
@SPITZGITHUB 

Ich habe [hier](https://bropat.github.io/ioBroker.eufy-security/#/authentication) die neue Dokumentation online genommen. Bitte lies den verlinkten Kapitel zur Authentifizierung und befolge die Anweisungen.

Falls etwas nicht klar sein sollte oder trotzdem nicht funktionieren, einfach hier melden.
