### ISSUE TITLE
Ringing event does not trigger

### ISSUE THREAD

**Issue by Pongard** [bropat/ioBroker.eufy-security#198]
I updated a bunch of stuff on my raspberry yesterday, so not totally sure if it was the update of this adapter.
But since yesterday, the ringing sensor event does not trigger anymore (as it seems). My scripts are still there, but when I ring the bell, the scripts do not trigger.

Any idea? Is it tested that the ringing event should work with the latest version?

Thanks for this amazing adapter

**Comment by bropat** [comment]
Set the adapter in [debug mode](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) and check that the push notifications arrive. If they do not arrive, check in the Eufy app that you have enabled them for ringing.

**Comment by bropat** [comment]
stale
