### ISSUE TITLE
Feature Request: Motion detection

### ISSUE THREAD

**Issue by ubieberich** [bropat/ioBroker.eufy-security#2]
**Describe the Feature**  
Eufycam generates a "motion detected" event. This event should be an alert object in iobroker.
In Apple Homekit every Eufy cam is also listed as an motion detector.

**Comment by bropat** [comment]
Hi ubieberich,

i'm working on it. Soon i will release a new version.

**Comment by bropat** [comment]
> Hi ubieberich,
> 
> i'm working on it. Soon i will release a new version.

In the meantime the push notifications aren't working anymore. The push notifications are the basis for implementing the movement detection... :(
I'm investigating the issue with @JanLoebel [here](https://github.com/JanLoebel/eufy-node-client/issues/9).

**Comment by bropat** [comment]
Hi,

i've released the new version (0.0.2) with integrated push notification. Can you check if you get a push notification when motion is detected?

Thanks!

**Comment by lk911lk** [comment]
Hi, wie kommen die Nachrichten dann?

Was soll ich genau machen?

**Comment by bropat** [comment]
Hi,

im Objektbrowser:

![image](https://user-images.githubusercontent.com/2305255/99906737-fcc10b80-2cd8-11eb-9e0c-a5cac1a01539.png)

Am besten den Adapter im Debug-Modus betreiben und einige Events simulieren, dabei solltest du hier die Benachrichtigungen bekommen. Bei Fehlern einfach mir die Logs zusenden.

**Comment by bropat** [comment]
A motion event is communicated once via a push notification.
Does anyone have any suggestions on how I can best integrate this into ioBroker?

@ubieberich How should I integrate this "one-time" event? Unfortunately you only get "Motion detected", but no message that the motion is finished.

**Comment by bropat** [comment]
Feature integrated with version 0.0.5 released now. Please test it and let me know.

Thanks!
