### ISSUE TITLE
Keine Geräte mehr

### ISSUE THREAD

**Issue by 3RROR-TINO** [bropat/ioBroker.eufy-security#200]
Hi kann mir jemand erklären warum im IoBroker keine Geräte mehr Angezeigt werde
![IOBROKER](https://user-images.githubusercontent.com/74939265/143764645-0bc27033-1624-47cd-b17f-834ed8b3a66e.jpg)
n?

**Comment by LastCodeDE** [comment]
@3RROR-TINO sieht für mich so aus, als hättest du keine Verbindung zur Cloud.

Sieh dir sonst diesen Beitrag mal an:
https://github.com/bropat/ioBroker.eufy-security/issues/201

**Comment by bropat** [comment]
@3RROR-TINO 

Ich habe [hier](https://bropat.github.io/ioBroker.eufy-security/#/authentication) die neue Dokumentation online genommen. Bitte lies den verlinkten Kapitel zur Authentifizierung und befolge die Anweisungen.

Falls etwas nicht klar sein sollte oder trotzdem nicht funktionieren, einfach hier melden.

**Comment by 3RROR-TINO** [comment]
@bropat Also bei mir geht gar nichts mehr, hab es nun Probiert neuen Account aber geht nicht!

**Comment by 3RROR-TINO** [comment]
<html>
<body>


eufy-security.0 | PID | Zeit | debug | Nachricht
-- | -- | -- | -- | --
eufy-security.0 | 25801 | 2021-12-17 10:19:40.026 | error | Token error
eufy-security.0 | 25801 | 2021-12-17 10:19:40.025 | error | Status return code not 200 [{"status":204,"statusText":"No Content"}]
eufy-security.0 | 25801 | 2021-12-17 10:19:39.134 | info | starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.eufy-security, node: v12.22.4, js-controller: 3.3.21


</body>
</html>

**Comment by 3RROR-TINO** [comment]
Geht wieder habe neuste Version von Github nun gehts!
