### ISSUE TITLE
Captcha Abfrage

### ISSUE THREAD

**Issue by Trunks1982** [bropat/ioBroker.eufy-security#201]
Diese Meldung kommen, woran kann das liegen?

![Bildschirmfoto 2021-11-28 um 13 40 05](https://user-images.githubusercontent.com/62701386/143768115-e6410514-da5f-4e3e-b977-c8d183c662d4.png)

**Comment by LastCodeDE** [comment]
Bei mir ist es genau das gleiche Problem. Habe ich die Two-Factor Authentifizierung aktiviert, möchte er im gleichen Bereich einen valid_code haben. Diesen trage ich ein und bestätige Ihn, anschließend geschieht aber nichts. Stelle ich die Authentifizierung um erhalte ich genau das gleiche wie @Trunks1982 in seinem Screenshot beschrieben hat. 

Gibt es etwas spezielles das bei Captcha eingetragen werden soll?

**Comment by nicomania** [comment]
Ich denke, ich habe die gleichen Symptome. Habe aber nichts verstellt, auch keine 2FA. Habe eine T8200.
![image](https://user-images.githubusercontent.com/35151132/145535702-c529192d-46bf-4944-bcf5-ea7767bdb836.png)

**Comment by bropat** [comment]
@Trunks1982 @LastCodeDE @nicomania 

Ich habe [hier](https://bropat.github.io/ioBroker.eufy-security/#/authentication) die neue Dokumentation online genommen. Bitte lest den verlinkten Kapitel und befolgt die Anweisungen.

Falls etwas nicht klar sein sollte oder trotzdem nicht funktionieren, einfach hier melden.

**Comment by nicomania** [comment]
Bei mir ist der Adapter nicht gelb und ich habe keine Einträge mit captcha. Soll ich ein eigenes Thema aufmachen?

**Comment by bropat** [comment]
@nicomania 

Welche Version des Adapters hast du installiert?

**Comment by nicomania** [comment]
0.7.1 stable

**Comment by bropat** [comment]
@nicomania 

Es gibt keine stable, nur beta. Update bitte auf der Version 0.7.5.

**Comment by nicomania** [comment]
Funktioniert prima, danke!
