### ISSUE TITLE
T8131 Fehlermeldung im Log bei Bewegung

### ISSUE THREAD

**Issue by Baenker** [bropat/ioBroker.eufy-security#203]
Bekomme bei Bewegung immer Fehler im Log

`eufy-security.0	2021-12-07 19:12:14.451	info	(25067) Disconnected from station T8131N63xxxxxx
eufy-security.0	2021-12-07 19:12:04.631	error	(25067) Station: T8131N63xxxxxx command CMD_PING failed with error: ERROR_CONNECT_TIMEOUT (-134)
eufy-security.0	2021-12-07 19:12:04.630	warn	(25067) Station T8131N63xxxxxx - Command aged out from queue [{"commandType":1139,"channel":255,"ageing":16480828,"maxAgeing":45000}]
eufy-security.0	2021-12-07 19:12:04.630	error	(25067) Station: T8131N63xxxxxx command CMD_PING failed with error: ERROR_CONNECT_TIMEOUT (-134)
eufy-security.0	2021-12-07 19:12:04.629	warn	(25067) Station T8131N63xxxxxx - Command aged out from queue [{"commandType":1139,"channel":255,"ageing":16481827,"maxAgeing":45000}]
eufy-security.0	2021-12-07 19:12:04.628	info	(25067) Connected to station T8131N63xxxxxx on host 192.168.178.90 and port 20134
eufy-security.0	2021-12-07 19:11:28.322	info	(25067) Downloading video event for device T8131N6321232CC4 in 31.282 seconds...
eufy-security.0	2021-12-07 19:11:28.321	info	(25067) Retry get image in 5 seconds from url: https://security-app-eu.eufylife.com/v1/x/x/xxx-xxxx (retry_count: 1 error: Not Found message: Not Found)..`

wenn ich die URL aufrufe kann ich ganz normal das Foto sehen. Dort verstehe ich die Meldung Not Found nicht.

Command aged out from queue  deutet für mich darauf hin das die Kamera nicht richtig erreichbar ist? Mit der App habe ich zu keinen Zeitpunkt ein Problem mit der Kamera

**Comment by bropat** [comment]
Welche Version des Adapters hast du installiert?

**Comment by Baenker** [comment]
0.75 war aber bei der Version davor auch so. Der Logeintrag T8131N63xxxxxx command CMD_PING failed with error: ERROR_CONNECT_TIMEOUT  kommt auch wenn ich z . B. eine Einstellung ändern will.

**Comment by bropat** [comment]
Um das Problem genauer analysieren und beheben zu können, benötige ich Zugriff mit Admin-Rechte auf die Kamera.
Falls du bereit bist mir diese über der Eufy App freizugeben:

patrick.broetto+eu3@gmail.com

Sag mir Bescheid.

**Comment by Baenker** [comment]
Freigabe erteilt. Mir würde es ja reichen wenn ich ausschließlich die Sicherheit einstellen kann von Deakiviert, Anwesend bis Deaktiviert.

**Comment by bropat** [comment]
Ich habe gerade von meiner ioBroker Instanz einen Test durchgeführt und es hat korrekt funktioniert.
Bei Solo Kameras wird die P2P-Verbindung nicht aufrecht erhalten, da ansonst die Batterie darunter leiden würde. So im Konkreten Fall wird bei einem Befehl die P2P-Verbindung kurz aufgebaut, der eine oder mehrere Befehle abgearbeitet und die Verbindung geschlossen.

Ich habe den Sicherheitsmodus von Abwesend in zu Hause und dann nochmal auf Abwesend geschalten ohne Fehler.

Funktionieren bei dir überhaupt keine Befehle? Wenn ja, hast du eine besondere Netzkonfiguration die den UDP-Verkehr blockiert?

**Comment by Baenker** [comment]
Bin gerade mal raus damit die Kamera eine Bewegung erkennt. Jetzt habe ich wieder Fehler im log. Ab und an funktionieren die Befehle aber nicht immer. Habe kein Muster erkannt. Bei Dir müsste aber jetzt auch Dein log Fehler anzeigen vom Video Download oder? Keine spezielle Netzwerk-Konfiguration bei mir. Habe eine Fritzbox 6590 und einen Repeater als Mesh. Sonos ist im Netz eingebunden und nutz wenn ich mich nicht täusche ebenfalls UDP? Dort gibt es keine Probleme.

**Comment by bropat** [comment]
Kannst du bitte nochmal eine Bewegung erzeugen?

**Comment by Baenker** [comment]
Habe gerade auch nochmal den Modus getestet. Ging in beide Richtung sofort. Also erst per ioBroker wurde sofort in der App angezeit und und dann per App. Bewegung erzeuge ich in ca. 5 Sekunden….

**Comment by bropat** [comment]
Also zum Fehler:

```
2021-12-14 17:58:24.196 - info: eufy-security.0 (12003) Retry get image in 5 seconds from url: https://security-app-eu.eufylife.com/v1/s/g/XXXXXXXX (retry_count: 1 error: Not Found message: Not Found)...
```

Hier kommt die Push Nachricht schneller an, als das das Bild seitens Eufy Cloud generiert wird. Aber gleich darauf wird nochmals probiert und das Bild wird heruntergeladen.

Hier kann man nicht mehr machen ;)

Der Download-Befehl war nicht erfolgreich:

```
2021-12-14 17:58:53.660 - debug: eufy-security.0 (12003) [Station.startDownload] Sending start download command to station T8131XXXXX for device T8131XXXXX with value: /media/mmcblk0p1/Camera00/20211214175823.h264
...
2021-12-14 17:59:27.050 - warn: eufy-security.0 (12003) Station T8131XXXXX - Tried all hosts, no connection could be established
2021-12-14 17:59:27.050 - info: eufy-security.0 (12003) Timeout connecting to station T8131XXXXX 
2021-12-14 17:59:27.051 - debug: eufy-security.0 (12003) [Station.scheduleReconnect] Schedule reconnect to station T8131XXXXX... [{"delay":5000}]
...
2021-12-14 18:00:02.076 - warn: eufy-security.0 (12003) Station T8131XXXXX - Tried all hosts, no connection could be established
2021-12-14 18:00:02.077 - info: eufy-security.0 (12003) Timeout connecting to station T8131XXXXX 
2021-12-14 18:00:02.077 - debug: eufy-security.0 (12003) [Station.scheduleReconnect] Schedule reconnect to station T8131XXXXX... [{"delay":10000}]
...
2021-12-14 18:00:30.669 - info: eufy-security.0 (12003) Connected to station T8131XXXXX on host 95.223.221.107 and port 23352
2021-12-14 18:00:30.670 - debug: eufy-security.0 (12003) [Station.getCameraInfo] Sending get camera infos command to station T8131XXXXX
2021-12-14 18:00:30.670 - warn: eufy-security.0 (12003) Station T8131XXXXX - Command aged out from queue [{"commandType":1024,"nestedCommandType":1024,"channel":0,"ageing":97008,"maxAgeing":45000}]
2021-12-14 18:00:30.670 - debug: eufy-security.0 (12003) [Station.onCommandResponse] Got p2p command response [{"station":"T8131XXXXX ","commandType":1024,"channel":0,"returnCodeName":"ERROR_CONNECT_TIMEOUT","returnCode":-134}]
2021-12-14 18:00:30.671 - error: eufy-security.0 (12003) Station: T8131XXXXX command CMD_DOWNLOAD_VIDEO failed with error: ERROR_CONNECT_TIMEOUT (-134)
```

Ich denke das Problem ist, dass die Solo Kamera, da sie keine zentrale Station verwendet wie andere Batterie betriebene Kameras, sich nicht so oft aufwecken lässt. Zumindest sieht es so im Log aus.
Weiß im Moment nicht wie man es besser machen könnte, ohne die Batterie zu belasten, bin aber für jegliche Vorschläge offen ;)

**Comment by bropat** [comment]
Es sieht so aus als ob sie erst nach 1 Minute wieder zur Verfügung steht. Es könnte ein "Stromsparmechanismus" sein den Eufy eingebaut hat, damit die Kamera nicht zu oft "geweckt wird".

Genau in diesem Zeitintervall müsstest du überprüfen ob die Eufy App noch funktioniert. Meines erachtens auch nicht.

**Comment by Baenker** [comment]
Für mich wäre ja eine Option wenn ich den Download einfach komplett deaktivieren kann. Somit sollte der Fehler weg sein und alles wäre gut :-)

Wie soll ich nun was testen? Ich erzeuge eine Bewegung und gucke dann in der App? Das funktioniert. Ich bekomme ja eine Push bei der Bewegung. Wenn ich dann die Push anklicke öffnet sich die App und ich sehe das Video. Bisher habe ich noch keinen Augenblick gehabt wo die App nicht funktioniert wo ich keinen Zugriff hatte.

**Comment by bropat** [comment]
> Für mich wäre ja eine Option wenn ich den Download einfach komplett deaktivieren kann. Somit sollte der Fehler weg sein und alles wäre gut :-)

Das ist leicht machbar ;) Ich werde dir eine Option in der nächsten Version hinzufügen.

> Wie soll ich nun was testen? Ich erzeuge eine Bewegung und gucke dann in der App? Das funktioniert. Ich bekomme ja eine Push bei der Bewegung. Wenn ich dann die Push anklicke öffnet sich die App und ich sehe das Video. Bisher habe ich noch keinen Augenblick gehabt wo die App nicht funktioniert wo ich keinen Zugriff hatte.

Alles was bis heute da ist wurde durch Reverse Engineering implementiert, somit ist leicht möglich das noch nicht alles reibungslos funktioniert. Weiters sind nicht alle Eufy Geräte von Eufy gleich entwickelt.

**Comment by Baenker** [comment]
Ja das habe ich schon bemerkt habe noch eine indoor 2K  pan&tild und es ist schon lustig das die teils unterschiedliche Bedienfunktionen haben. Alleine das Menü beim Livebild ist anders aufgebaut.

Auch lustig das man bei der E40 die Videos nicht in die eufycloud Speichern kann sondern nur auf den verbauten Speicher.

Ich finde es schade das die Anker keine offizielle Api anbietet. Gleichzeitig natürlich mein Riesendank das Du Dir soviel Mühe machst.

**Comment by RoPo88** [comment]
Servus,
Ich hatte das gleiche Problem, dass bei einer Bewegung eine Fehlermeldung im ioBroker kam.
In einem anderen Thread hatte ich gelesen dass der Fehler nicht mehr auftaucht, wenn man die Push-Nachricht ausschaltet. Habe es probiert und es hat funktioniert.

Bei beheben des nächsten Problems habe ich irgendwie den Adapter zerschossen und die Geräte aus der Smartphone App gelöscht.
Daraufhin habe ich alles von meinem ioBroker runter geschmissen, in der Smartphone App alles auf Werkseinstellung zurückgesetzt dann als erstes den Adapter und die Instanz angelegt und konfiguriert und zum Schluss die die App auf dem Smartphone konfiguriert.
Lustigerweise bekomme ich jetzt auch keine Fehler im ioBroker obwohl ich die Push-Nachricht an aktiviert habe. 

Keine Ahnung woran das liegt.

**Comment by bropat** [comment]
Ich habe gerade Version 0.8.0 veröffentlicht die die Kommunikation mit der Kamera T8131 etwas stabilisieren sollte. Weiters gibt es in der neuen Version auch die Möglichkeit, dass automatische herunterladen des Videos über P2P zu deaktivieren.

Ich schließe mal diese Issue. Falls trotzdem noch Probleme auftreten, einfach eine neue Issue öffnen.

**Comment by Baenker** [comment]
Vielen Dank

**Comment by Baenker** [comment]
Kurzer Nachtrag @bropat ich entziehe Dir den Zugriff zur Kamera erstmal wieder. Falls Du ihn später oder jetzt noch brauchst einfach bei mir melden. Schalte Dich jederzeit frei falls Du die Kamera als Testobjekt brauchst…

**Comment by bropat** [comment]
@Baenker ok, Danke!
