### ISSUE TITLE
[Question]: Alternative option to retrieve captcha?

### ISSUE THREAD

**Issue by box99h** [bropat/ioBroker.eufy-security#210]
### Ask your question

Hi,

for some reason the download and decoding of the current log is badly slow using the described method in the tutorial. I've already stopped all adapters beside the Eufy, without success. 
Actually I don't have a chance to get the captcha within the 30s threshold, as displaying the log is already taking more than the 30s.. Is there an alternative option to see the captcha. Downloading the .log via ssh is possible and finished within a fraction of a second. But opening the downloaded log will not decode the captcha and I only see a long string.

Thank you

**Comment by bropat** [comment]
In the last version (0.8.0), a state "received_captcha_html" was added for this purpose, where you can get the captcha code in HTML format.
