### ISSUE TITLE
[Bug]: Verification Code for 2FA has to be string not number in order to work

### ISSUE THREAD

**Issue by Claus1985** [bropat/ioBroker.eufy-security#212]
### Adapter version

0.7.4

### JS-Controller version

3.3.22

### Node version

14.18.2

### Operating System type

Linux

### Operating system version

Raspbian Buster

### Describe the bug

I got several errors when I attempted to get the adapter to work with 2FA until I found out that the verification code has to be a string and not a number. Please correct type in the adapter.

Thx!

### To reproduce

Send verification code as number > Error
Send verification code as string > success

**Comment by bropat** [comment]
@This bug has already been fixed in version 0.7.4. See [here](https://github.com/bropat/ioBroker.eufy-security/blob/a76933779d9c0a3fe9c935914502ee8e6f16729d/src/lib/utils.ts#L387-L403).
