### ISSUE TITLE
Guard Mode can only be changed from Objects view (not via cli, mqtt...)

### ISSUE THREAD

**Issue by MaxWinterstein** [bropat/ioBroker.eufy-security#35]
**Describe the bug**  
I tried to change the `Guard Mode` via MQTT to build some kind of bridge between ioBroker and Home Assistant. But when I change the value of `guard_mode` from anywhere except the ioBroker Objects view it seems not to get submitted. The Object view shows new value, but it will be replaced by the old value on next pull. 

I know you are not the HomeAssistant guy, but this can be broken down to a non HomeAssistant related issue.

**To Reproduce**  
Easiest way is to reproduce via the iobroker command line.

0. Have homebase Guard Mode set to Home(1)
1. Get access to a ioBroker CLI. (As I use docker, I simply run a fresh `/bin/sh` and attach myself
2. run `iobroker state set eufy-security.0.T8010NXXXXXXXXXX.station.guard_mode 0 true`  
  response: `The state "eufy-security.0.T8010NXXXXXXXXXX.station.guard_mode" was set to "0" with flag ack=true`
3. Observe the change to the new Value at the Objects view
3. Wait max. one pull interval
4. Value changes back to old one

**Expected behavior**  
Value should be set to new one, stay the new one and App should reflect the new value.

**Screenshots & Logfiles**  
Only log line that shows up is:  

> eufy-security.0 | 2020-12-25 11:14:58.611 | info | (4299) state eufy-security.0.T8010NXXXXXXXXXX.station.guard_mode changed: 1 (ack = true)

**Versions:**  
 - Adapter version: 0.0.8
 - JS-Controller version: 3.1.6
 - Node version: 12.19.1
 - Operating system: Docker Container, Debian 10 Based https://hub.docker.com/r/buanet/iobroker/

**Additional context**  
I guess there is some trigger(?) missing as it seems the command is only setting the current state but not publishing the new state to the servers.

Grüße aus Frankfurt am Main
Max

**Comment by MaxWinterstein** [comment]
Oh, seems like I am too unaware of the ack stuff :(

`iobroker state set eufy-security.0.T8010NXXXXXXXXXX.station.guard_mode 0 false` works fine. 

Still not sure how to get that running with MQTT...

**Comment by bropat** [comment]
For generic ioBroker help please use the ioBroker forum.
