### ISSUE TITLE
Feature request: integration for home assistant

### ISSUE THREAD

**Issue by skank01** [bropat/ioBroker.eufy-security#36]
Hi great work !

Any chance ur willing to make this for home assistant?

**Comment by bropat** [comment]
@skank01
As already said on #14 and #18:

I'm sorry, but unfortunately not. My main focus is on ioBroker.

Why not switch to ioBroker? ;)

**Comment by bropat** [comment]
For a possible integration see this [post](https://blog.fuzzymistborn.com/controlling-eufy-security-devices-with-iobroker/).

Credits goes to @FuzzyMistborn
