### ISSUE TITLE
Code 255 beim Wechel des Guard_Mode

### ISSUE THREAD

**Issue by tofrie** [bropat/ioBroker.eufy-security#46]
Beim Wechsel des Guardmode werden die Zahlen 255 statt 1 oder 0 geschrieben. In der App gibt es keinen Status mehr.

![AACF3DDE-50B7-4B0D-AFFA-0155C4280B1F](https://user-images.githubusercontent.com/60553702/103536818-7da42300-4e93-11eb-955b-21821060cfad.png)

**Comment by bropat** [comment]
@tofrie Kannst du mir bitte die Debug-Logs per Mail zusenden?

Danke!

**Comment by tofrie** [comment]
Die Mail ist raus. Ich hoffe du kannst etwas mit anfangen.

**Comment by tofrie** [comment]
Ich vermute, dass es an dem Skript liegt. Es prüft bei einer Änderung vom Alarmstatus den Wert und schreibt entweder eine 0 oder 1 in den Guard_Mode. Hierbei tritt der Fehler auf. Ein Wechsel unter Objekte, per Dropdown-Menü, funktioniert ohne Probleme.

**Comment by bropat** [comment]
@tofrie 

Ja das Problem liegt an einem Javascript Skript:

```
2021-01-04 04:26:16.173  - [33mwarn[39m: javascript.0 (24201) You are assigning a string to the state "eufy-security.0.T8010N232025099F.station.guard_mode" which expects a number. Please fix your code to use a number or change the state type to string. This warning might become an error in future versions.
2021-01-04 04:26:16.203  - [33mwarn[39m: javascript.0 (24201)     at Object.setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1358:20)
2021-01-04 04:26:16.203  - [33mwarn[39m: javascript.0 (24201)     at setStateDelayed (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1402:25)
2021-01-04 04:26:16.205  - [33mwarn[39m: javascript.0 (24201)     at Object.<anonymous> (script.js.Eufy_neu:7:5)
2021-01-04 04:26:16.205  - [33mwarn[39m: javascript.0 (24201)     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
2021-01-04 04:26:16.206  - [33mwarn[39m: javascript.0 (24201)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
2021-01-04 04:26:16.206  - [33mwarn[39m: javascript.0 (24201)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
2021-01-04 04:26:16.207  - [33mwarn[39m: javascript.0 (24201)     at processImmediate (internal/timers.js:461:21)
```

Im Moment wird vom Adapter der gesetzt Wert noch nicht überprüft und somit wenn z.B. ein Skript einen Guard Modus mit Wert 255 setzt, dann erlaubt dies der Adapter und es kommt zu deinem Fehlverhalten. In der nächsten Version werde ich dies vorher schon abfangen und dafür einen Fehler im Log generieren. ;)

**Comment by tofrie** [comment]
@bropat das Skript setzt aber nur eine 1 oder 0. woher kommt dann die 255?

**Comment by bropat** [comment]
@bropat 

Wenn du mir den Kode des Skriptes sendest, kann ich dir den Fehler finden, andernfalls kann ich dir nur sagen, dass dem Adapter der Wert 255 übergeben wird und er versucht diesen dann zu setzen ;).

**Comment by tofrie** [comment]
@bropat so sieht der Code aus:
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="on" id="_^D[az)e=qcT#i?L.P!!" x="113" y="88">
    <field name="OID">lupusec.0.status.mode_pc_a1</field>
    <field name="CONDITION">any</field>
    <field name="ACK_CONDITION"></field>
    <statement name="STATEMENT">
      <block type="controls_if" id="fU)s]tW;Cg8b[.O*.:}t">
        <mutation elseif="1"></mutation>
        <value name="IF0">
          <block type="logic_compare" id="bKWHd*i0g/G{[sk,~Cgh">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="get_value" id="g5;B0%AevyO~6,Pu*wD4">
                <field name="ATTR">val</field>
                <field name="OID">lupusec.0.status.mode_pc_a1</field>
              </block>
            </value>
            <value name="B">
              <block type="text" id="H3C^wHBHXLP~dVv[%HYw">
                <field name="TEXT">1</field>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO0">
          <block type="control_ex" id=".Hi_)a_2#*cSw_9@_e#v">
            <field name="TYPE">false</field>
            <field name="CLEAR_RUNNING">FALSE</field>
            <value name="OID">
              <shadow type="field_oid" id="rJ9RSb~xvxsVfR_#J0QZ">
                <field name="oid">eufy-security.0.T8010N232025099F.station.guard_mode</field>
              </shadow>
            </value>
            <value name="VALUE">
              <shadow type="logic_boolean" id="9Lo2A!X*Akli6e]WH!xT">
                <field name="BOOL">TRUE</field>
              </shadow>
              <block type="text" id="B$|*bE}D7wNz+Hxhk[Ks">
                <field name="TEXT">0</field>
              </block>
            </value>
            <value name="DELAY_MS">
              <shadow type="math_number" id="(soll,O3+-B9@~MfAq1;">
                <field name="NUM">0</field>
              </shadow>
            </value>
          </block>
        </statement>
        <value name="IF1">
          <block type="logic_compare" id="zFibE~4Y]dQ?0a,7I.Pa">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="get_value" id="By#gs0d9CY?}jVCk`yVS">
                <field name="ATTR">val</field>
                <field name="OID">lupusec.0.status.mode_pc_a1</field>
              </block>
            </value>
            <value name="B">
              <block type="text" id="dn(ZoohU2manSE-WMA#D">
                <field name="TEXT">0</field>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO1">
          <block type="control_ex" id="G/{?hczY$7MCj?/NAc3Z">
            <field name="TYPE">false</field>
            <field name="CLEAR_RUNNING">FALSE</field>
            <value name="OID">
              <shadow type="field_oid" id="G7s7`;NJ4.M[ulk3_Jbi">
                <field name="oid">eufy-security.0.T8010N232025099F.station.guard_mode</field>
              </shadow>
            </value>
            <value name="VALUE">
              <shadow type="logic_boolean">
                <field name="BOOL">TRUE</field>
              </shadow>
              <block type="text" id="#+Rv2}Gg`_pNpdQX5o(A">
                <field name="TEXT">1</field>
              </block>
            </value>
            <value name="DELAY_MS">
              <shadow type="math_number" id="{AS5%1UnsjjqMOhJlqn%">
                <field name="NUM">0</field>
              </shadow>
            </value>
          </block>
        </statement>
      </block>
    </statement>
  </block>
</xml>

**Comment by tofrie** [comment]
@bropat ich habe es dir auch per Mail geschickt weil es hier nicht vollständig zu lesen ist.

**Comment by bropat** [comment]
@tofrie 

Der Typ des Feldes stimmt für `guard_mode`nicht:

`<field name="TEXT">1</field>`

sollte sein:

`<field name="NUM">1</field>`

selbe für 0...

**Comment by tofrie** [comment]
Super, vielen Dank. Es funktioniert wieder alles. Zu meiner Verteidigung sei gesagt, dass ich Anfänger bin 😊
