### ISSUE TITLE
	(2716513) handlePushNotifications(): Error: Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Stormbringer11** [bropat/ioBroker.eufy-security#50]
Hallo Bropat,

bei der aktuellen Version vom Adapter bleiben die Bewegungsstates (Person erkannt) "kleben" und funktionieren im Vergleich zu den älteren Versionen (glaub war auf 0.0.8 vorher) nicht mehr zuverlässig. Im LOG taucht immer wieder folgender Error auf:

(2716513) handlePushNotifications(): Error: Error: Request failed with status code 404

Wäre nett, wenn du dir das mal anschauen könntest. Danke :o)

**Comment by bropat** [comment]
@Stormbringer11 

Kannst du es nochmal mit der gerade veröffentlichten Version versuchen (0.1.4)?
Falls du trotzdem noch Fehler erhältst, bitte den Adapter im [Debug-Modus versetzten](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug), Fehler reproduzieren und mir dann bitte die Logs zusenden.

**Comment by Stormbringer11** [comment]
Du bist ja flott, danke :o) Habs geladen im moment schaut es gut aus, ich teste mal.

**Comment by Stormbringer11** [comment]
Bleibt leider noch immer "kleben". LOG auf Debug hätte ich.... Kann ich das einfach hier posten oder sind da sensible Daten drinnen damit jeder dann auf die Kameras zugreiffen kann?

**Comment by bropat** [comment]
@Stormbringer11 
Bitte nicht hier posten da sensible Daten enthalten sind (hauptsächlich der Auth-Token!). Einfach mir per Mail zusenden.

**Comment by Stormbringer11** [comment]
Ok und auf welche Adresse kann ich es dir mailen?

**Comment by bropat** [comment]
Im Readme des Repos ganz unten unter Lizenz findest du meine Mail. :)

**Comment by Stormbringer11** [comment]
erledigt ;o)

**Comment by bropat** [comment]
@Stormbringer11 
Habe die Ursache gefunden werde in den nächsten Tagen eine Fix veröffentlichen.

**Comment by Stormbringer11** [comment]
Super danke 🙃👍
