### ISSUE TITLE
(19951) unhandled promise rejection: Request failed with status code 404

### ISSUE THREAD

**Issue by skywalker3201** [bropat/ioBroker.eufy-security#53]
Hallo Bropat,

seit gestern bekomme ich keine Verbindung mehr zum Adapter. Im Log taucht immer folgender Fehler auf: 

Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

(19951) unhandled promise rejection: Request failed with status code 404

(19951) Error: Request failed with status code 404 at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/axios/lib/core/settle.j

Status iobroker:
verbunden mit eufy, der Rest negativ (steht auf rot)

Folgendes habe ich schon versucht: Alle beteiligten Geräte neu gestartet. Adapter deinstalliert. Neueste Version (heute) installiert.

Was könnte das Problem sein? Habe an Hard- und Software prinzipiell nichts verändert.

Viele Grüße

**Comment by bropat** [comment]
Hallo @skywalker3201 ,

bitte den Adapter im [Debug-Modus](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) versetzten, Fehler reproduzieren und mir dann bitte die Logs per Mail zusenden (die Mailadresse findest du im Readme des Repos ganz unten unter Lizenz).

**Achtung:** Im Log sind sensible Daten enthalten (hauptsächlich der Token). Bitte entfernen/redigieren.

**Comment by bropat** [comment]
Ich denke die Ursache ist die selbe wie hier: #50

**Comment by skywalker3201** [comment]
Sehr gut, hoffentlich funktioniert es. Der Adapter an sich ist super!
