### ISSUE TITLE
Eufy 1 and Homebase 1 working

### ISSUE THREAD

**Issue by dezmui** [bropat/ioBroker.eufy-security#58]
Great work with the adapter! 
Just letting you know, I've got the Eufy 1 Camera (T8111) and Homebase 1 (T8001) and both are working perfectly fine.

**Comment by bropat** [comment]
@dezmui Thank you for your feedback.

I will soon release a test version that supports livestream over the local station using the nativ p2p protocol, producing an HLS stream for playback. I need some testers, are you interested?

**Comment by dezmui** [comment]
Sure, would love to help test

**Comment by bropat** [comment]
I'll let you know as soon as I'm ready.

**Comment by bropat** [comment]
@dezmui Added device and station to known working devices.

I just released the new version (0.2.0) with livestream over p2p. Please test and let me know :)

**Comment by dezmui** [comment]
@bropat Took me a while to get some free time to test this. Works just fine thanks!

I can't remember how close to realtime the previous implementation was, but this one is about 20 seconds behind. Is this the expected lagtime for viewing the m3u8 stream?

**Comment by bropat** [comment]
@dezmui 
It depends very much on the connectivity to the camera and the processing power of the system where ioBroker is running, since the data received from ffmpeg is "converted" live to an HLS stream.

If you put the adapter in [debug mode](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug), start the stream and then send me the logs, I can check.

**Comment by dezmui** [comment]
That's fair enough. I'm running ioBroker on a Synology 1019+ NAS via Docker, and my camera is wireless. So that makes sense. No complaints though, I think this is just expected considering my circumstances. 👍

**Comment by bropat** [comment]
@dezmui 
I have dug deeper to understand what else could be the cause of such a delay and I think I have found it.
The embedded ffmpeg version does not support hw transcoding :-(
I will add the possibility to configure a custom ffmpeg in the adapter in a next release. So everyone can configure and use the "best" ffmpeg version by himself.
