### ISSUE TITLE
Zweite Bearbeitung im Adapter

### ISSUE THREAD

**Issue by Trunks1982** [bropat/ioBroker.eufy-security#6]
Hi wollte nochmal drauf hinweisen das man nur einmal im Adapter die Zugangsdaten eingeben kann.Wenn man sie wieder auslöscht und neu eingibt, funktioniert das abspeichern nicht mehr

**Comment by bropat** [comment]
Hallo,

kann diesen Fehler mit der aktuellen Version (0.0.2) nicht nachvollziehen. Ist er noch vorhanden?

Grüße
Patrick

**Comment by Trunks1982** [comment]
Auch in 0.0.3 ist dieser Fehler.Gehe ich in den Adapter rein um Passwort usw zubearbeiten, wird mir nichts angezeigt bzw kann nicht bearbeiten und speichern.

**Comment by bropat** [comment]
Kannst du mir bitte die Logs zusenden?

Welche Version hast du von:

- Node.js
- js-controller
- iobroker.admin

**Comment by Trunks1982** [comment]
hab dir gerade zukommen lassen.Alles neuste version

**Comment by bropat** [comment]
Ich kann dieses Problem einfach nicht nachstellen :-(
Kannst du mir vielleicht Schritt für Schritt alles dokumentieren (mit Bildern) und mir es per Mail zukommen lassen?

Hat vielleicht noch jemand anders das selbe Problem?

Danke nochmals!

**Comment by Trunks1982** [comment]
<img width="2365" alt="Bildschirmfoto 2020-11-24 um 09 47 14" src="https://user-images.githubusercontent.com/62701386/100070326-175ec600-2e3a-11eb-92d5-ba5ccecfed17.png">

Wenn man den Adapter installiert und die Eingaben Benutzer und Passwort gemacht hat.Abspeichern und dann wieder aufruft kommt das Bild was man oben sehn kann.

**Comment by bropat** [comment]
In Version 0.4.1 behoben :)
