### ISSUE TITLE
Feature request - Homebridge 

### ISSUE THREAD

**Issue by ummario** [bropat/ioBroker.eufy-security#60]
Hello... sorry to ask, maybe I'm making a silly question, since I'm totally new to NMP and Homebrigde as well. Is there any way I install this package on Homebridge? I really need to find a way to control Eufy door sensors on Apple HomeKit. Thanks

**Comment by bropat** [comment]
Hi @ummario,
I'm sorry, but this adapter is only compatible with ioBroker and not with Homebridge.
