### ISSUE TITLE
Create MP4

### ISSUE THREAD

**Issue by TbsJah** [bropat/ioBroker.eufy-security#64]
Es ist möglich den rtsp stream in eine mp4 zu wandeln 
`ffmpeg -i rtsp://user:password@192.xxx.xxx.xx/live3 -r 10 -t 60 -vcodec copy -acodec copy -y /opt/iobroker/OUT.mp4`

Evtl kann das in den Adapter eingebunden werden

Leider ist der rtsp stream nicht immer abgreifbar
Da muss er erst wieder neu gestartet werden

**Comment by TbsJah** [comment]
Funktioniert mit
`ffmpeg -i "rtmp://p2p-vir-8.eufylife.com/hls/........time=11111111&token=123456....." -c copy -flags +global_header -f segment -segment_time 60 -segment_format_options movflags=+faststart -reset_timestamps 1 /opt/iobroker/test%d.mp4`

**Comment by bropat** [comment]
Hi @TbsJah,

zur Zeit arbeite ich genau am live streaming über P2P (nicht zu verwechseln mit den RTMP stream; sprich direkt von der Station/Device). Der aktuelle Stand ist, dass ich bereits ein Video mit Audio über P2P von der Station empfange und mit ffmpeg in einem HLS stream konvertiere. :)
ffmpeg wurde von mir bereits integriert (es wurde nur noch nichts veröffentlicht). Sobald ich diesen Teil fertig entwickelt habe werde ich eine neue Version veröffentlichen.

**Comment by bropat** [comment]
@TbsJah Ich habe gute Neuigkeiten. Der Livestream über P2P funktioniert nun auch :)
Sobald die neue Version bereit ist, werde ich sie veröffentlichen.

**Comment by TbsJah** [comment]
Absolut Mega
Danke für deine Arbeit!

**Comment by bropat** [comment]
@TbsJah Die neue Version (0.2.0) mit Livestream über P2P wurde veröffentlicht. Bitte testen und falls es Probleme gibt einfach neue Issue öffnen. Danke!

Grüße
