### ISSUE TITLE
Feature Request: An und Ausschalten der Kamera

### ISSUE THREAD

**Issue by CHPhilu** [bropat/ioBroker.eufy-security#69]
Es wäre toll wenn es die möglichkeit geben würde eie Kamera mittels button an oder auszuschalten.

**Comment by bropat** [comment]
Hi @CHPhilu ,

ist bereits geplant. Sobald diese Funktionalität veröffentlicht wird, gebe ich dir Bescheid.

**Comment by bropat** [comment]
Mit der Version 0.2.0 wurde diese Funktionalität implementiert.
