### ISSUE TITLE
Nur eine Homebase wird als Objekt beim ersten Einrichten ordentlich angelegt

### ISSUE THREAD

**Issue by thogens** [bropat/ioBroker.eufy-security#7]
**Describe the bug**  
Richtet man den Adapter das erste Mal ein, so erscheint nur eine Homebase mit den verbundenen Kameras korrekt unter den Objekten.
Meine zweite Homebase erscheint lediglich als "Datenpunkt" ohne weitere unterpunkte.

**Expected behavior**  
Es sollten für jede Homebase entsprechende Ordner nebst verbundener Kameras erstellt und angezeigt werden.

**Workaround**  
1 x ioBroker komplett restarten behebt das Problem

**Comment by bropat** [comment]
Hallo,

sollte mit der letzten Release (0.0.2) behoben sein.

Grüße
Patrick
