### ISSUE TITLE
Komplette URL für last_captured_pic_url und Last event picture URL

### ISSUE THREAD

**Issue by Tscherno** [bropat/ioBroker.eufy-security#75]
Hi,

in den States ist nur eine relative URL. Wie sieht eine komplette URL aus? Auf dem Admin-Webserver-Port liegt es auf jeden Fall nicht:
http://server.fritz.box:8081/eufy-security.0/last_captured_T8200N00193944F1.jpg
Cannot GET /eufy-security.0/last_captured_T8200N00193944F1.jpg

**Comment by cratoo** [comment]
Überlicherweise läuft das vis auf :8082.

**Comment by Tscherno** [comment]
Tatsächlich habe ich (bisher) gar kein VIS aktiv. Aber dann aktiviere ich das mal ;)

**Comment by Tscherno** [comment]
OK, jetzt funktioniert es halb:

last_event_pic_url liefert ein Bild zurück

last_captured_pic_url ein fehlerhaftes Bild:
![grafik](https://user-images.githubusercontent.com/5594674/107247466-99ba5780-6a31-11eb-857e-f93e8b82f900.png)

**Comment by cratoo** [comment]
Dürfte am Fehler aus meinem #71 Issues liegen.

**Comment by bropat** [comment]
> Hi,
> 
> in den States ist nur eine relative URL. Wie sieht eine komplette URL aus? Auf dem Admin-Webserver-Port liegt es auf jeden Fall nicht:
> http://server.fritz.box:8081/eufy-security.0/last_captured_T8200N00193944F1.jpg
> Cannot GET /eufy-security.0/last_captured_T8200N00193944F1.jpg

Hi @Tscherno,

der Grund für eine relative URL ist, dass ich damit jegliche Bedürfnisse abdecke. Bei einer absoluten URL hätte ich schon mal ein Problem wenn jemand einen Reverse proxy verwenden möchte.
Die Bilder / Livestreams / Videos werden nun alle über den Web Adapter zu Verfügung gestellt (typischerweise Port: 8082).

**Comment by greuff** [comment]
Hallo @bropat , bei mir ist leider das Problem dass auch auf :8082 die Files nicht aufrufbar sind. Dateien im Filesystem:

```
iobroker@openhab:/opt/iobroker/iobroker-data $ find eufy-security.0/
eufy-security.0/
eufy-security.0/T8010N2320430969
eufy-security.0/T8010N2320430969/last_live
eufy-security.0/T8010N2320430969/last_live/T8142N002039038413.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903843.ts
eufy-security.0/T8010N2320430969/last_live/T8142N0020390384.jpeg
eufy-security.0/T8010N2320430969/last_live/T8142N00203903842.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903848.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903844.ts
eufy-security.0/T8010N2320430969/last_live/T8142N002039038411.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903849.ts
eufy-security.0/T8010N2320430969/last_live/T8142N002039038412.ts
eufy-security.0/T8010N2320430969/last_live/T8142N002039038410.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903845.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903846.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903840.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903847.ts
eufy-security.0/T8010N2320430969/last_live/T8142N00203903841.ts
eufy-security.0/T8010N2320430969/last_live/T8142N0020390384.m3u8
eufy-security.0/T8010N2320430969/live
eufy-security.0/T8010N2320430969/last_event
eufy-security.0/T8010N2320430969/last_event/T8142N002039066E.jpeg
eufy-security.0/T8010N2320430969/last_event/T8142N0020390384.jpeg
eufy-security.0/T8010N2320430969/last_event/T8113N13204800CD.jpeg
eufy-security.0/persistent.json
```

Wert von `last_livestream_pic_url`: `eufy-security.0/T8010N2320430969/last_live/T8142N0020390384.jpeg`

Ausgabe im Browser wenn ich http://openhab.local:8082/eufy-security.0/T8010N2320430969/last_live/T8142N0020390384.jpeg aufrufe: `File T8010N2320430969/last_live/T8142N0020390384.jpeg not found: {}`

Installierte Adapter:

![image](https://user-images.githubusercontent.com/6804487/111906324-500d5580-8a50-11eb-9fbd-f79f23bf7d61.png)

Danke für jegliche Hilfe

**Comment by bropat** [comment]
Hi @greuff,

probiere einen manuellen (einmaligen) Upload des eufy-security Adapters wie [hier](https://www.iobroker.net/#de/documentation/tutorial/adapter.md?uploadvonadapterdateien) beschrieben. Dann sollte es funktionieren.

**Comment by greuff** [comment]
Hat funktioniert, danke!

Am 21. März 2021 17:59:19 schrieb bropat ***@***.***>:
