### ISSUE TITLE
Feature request: Alarm manuell über DP antriggern

### ISSUE THREAD

**Issue by Screambear** [bropat/ioBroker.eufy-security#76]
Hallo und danke für die super Arbeit!

ist es möglich das man die Homebase2 antriggern kann so das die den Alarm auslöst? So könnte man sie in ioBroker in eine Alarmanlage oder in Wasserlecksensoren einbinden.

**Comment by bropat** [comment]
Hallo @Screambear ,

ich weiß nicht ob dies möglich ist. Bis jetzt bin ich noch nicht über so eine Funktionalität im Quellcode gestoßen.

**Comment by bropat** [comment]
Ist leider nicht machbar.

**Comment by bropat** [comment]
Laut neusten Kenntnisstand sollte es machbar sein.

**Comment by Screambear** [comment]
Das wäre genial wenn es doch implementiert werden könnte.

bropat ***@***.***> schrieb am Mi., 9. Juni 2021, 20:48:

**Comment by bropat** [comment]
Diese Funktionalität wurde im Treiber bereits implementiert. In der nächsten Veröffentlichung des Adapters wird sie verfügbar sein. Ich arbeite gerade an einer neuen Version, so stay tuned ;)

**Comment by Screambear** [comment]
@bropat 

super! klasse arbeit von dir! berichte bitte wenn es drinne ist. teste es auch gerne.

**Comment by bropat** [comment]
@Screambear Released mit Version 0.6.0
