### ISSUE TITLE
Indoor cam 2k (T8400) wir nicht vollständig unterstützt

### ISSUE THREAD

**Issue by PatrickBreitMe** [bropat/ioBroker.eufy-security#77]
**Describe the bug**  
Das Model T8400 taucht im Adapter auf, jedoch fehlen einige Werte. 
Wie: wifi_rssi state oder Last picture Event 

der Rest funktioniert eigentlich 👍

![00A244B4-C07F-4117-B4DD-0ED72E399C11](https://user-images.githubusercontent.com/78851740/107499832-bbccea80-6b95-11eb-9dea-7c76ec0844b3.jpeg)

**Comment by FeromonDE** [comment]
Das gleiche Problem mit T8410

**Comment by bropat** [comment]
@PatrickBreitMe, @FeromonDE 
Könnt ihr bitte den Adapter im [Debug-Modus](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) versetzten, starten und mir dann die Logs zusenden? So kann ich nachsehen wo das Problem liegt.

**Comment by FeromonDE** [comment]
Hallo, hier sind die Logs.
Mit freundlichen Grüßen
Dmitrij Geller


ср, 24 февр. 2021 г. в 08:06, bropat <notifications@github.com>:

**Comment by FeromonDE** [comment]
@bropat, kann ich die Logs irgendwie per Private Nachricht zusenden?

**Comment by bropat** [comment]
@FeromonDE Nein leider nicht, außer du sendest mir eine Mail ;) (findest du [hier](https://github.com/bropat/ioBroker.eufy-security#license))

**Comment by FeromonDE** [comment]
@bropat 
Irgendwelche Updates? Ich habe update auf 0.3.0 gemacht. device_enabled state ist immer false, man kann auf true oder false setzen, und kamera wird ein-oder ausgeschaltet. Auf motion_detection gibt es keine Reaktion.

**Comment by bropat** [comment]
@FeromonDE 
Nicht wirklich, ich besitze keine Indoor cam, somit kann ich nichts testen und einige Funktionen wurden nur durch Reverse Engineering implementiert (ohne gewähr).
Ich kann qualitativ nur eine gutes Ergebnis liefern, wenn:

* Jemand mir für kurze Zeit ein Indoor cam über sharing in der Eufy App zu Verfügung stellt (am effektivsten!)
* Jemand spendet/sendet mir eine Cam

Alles andere führt nicht so schnell zum gewünschten Ziel.
Beim ersten Punkt kann man auch nur eine (oder mehrere, je nachdem) kurze Live Session gemeinsam machen.
Lasse mich Wissen ob du dabei Helfen möchtest. ;)

**Comment by FeromonDE** [comment]
> * Jemand mir für kurze Zeit ein Indoor cam über sharing in der Eufy App zu Verfügung stellt (am effektivsten!)

Das kann ich machen.

**Comment by bropat** [comment]
@FeromonDE Super :). Ich melde mich bei dir.

**Comment by bropat** [comment]
@FeromonDE Gast sollte reichen.

**Comment by bropat** [comment]
@FeromonDE Habe dir gerade eine Mail gesendet. ;)

**Comment by bropat** [comment]
@FeromonDE, @PatrickBreitMe 

Mit Version 0.4.0 sollte nun alles funktionieren (wifi rssi state für Indoor Kameras wurde zwischenzeitlich deaktiviert).

**Comment by FeromonDE** [comment]
@bropat leider werden die States nicht geupdatet. Z.B ich schalte Kamera aus, aber State von device_enabled bleibt auf true, egal was ich mache. Auch nach dem kompletten Restart von ioBroker.

**Comment by bropat** [comment]
Standardmäßig werden alle 10 min. die States aktualisiert im Adapter aktualisiert (einstellbar). Ein zeitnahes aktualisieren ist leider nicht möglich.
Sollte eigentlich funktionieren, hatte ich ja bei dir mit meiner ioBroker Testumgebung probiert...

**Comment by FeromonDE** [comment]
@bropat ich habe noch 2C Pro Kameras, wenn ich Kamera ausschalte und starte Instance neu, dann wechselt sich State auf false, für Indoor Kamera bleibt auf true, obwohl die auch ausgeschaltet ist.

**Comment by bropat** [comment]
Kannst du mir die debug logs zusenden?

Ich kann morgen nochmals alles überprüfen, wenn du mir wieder eine Freigabe machst.
