### ISSUE TITLE
Unable to View Any .m3u8 Streams

### ISSUE THREAD

**Issue by pldmgg** [bropat/ioBroker.eufy-security#79]
Using version 0.2.0

Toggling "start_stream" for Eufy Cam 2/2 Pro generates a livestream url tail similar to:

```
/eufy-security.0/T8010XXXXXXXXX/live/T8114XXXXXXXXX.m3u8
```

But when I try something similar to the following url, the stream does not actually load (it does not appear that this path actually exists on the webserver):

```
http://<IPAddress>:8082/eufy-security.0/T8010XXXXXXXXX/live/T8114XXXXXXXXXX.m3u8
```

I've tried with both VLC and in the Chrome browser.

(I can resolve other files via other paths like ```http://<IPAddress>:8082/eufy-security.0/T8210XXXXXXXXXX.jpg``` without issue)

**Comment by bropat** [comment]
Hi @pldmgg,
please activate the debug mode 2 of the adapter and reproduce the error. Then please send me the logfile (note: the logfile contains sensitive data; mainly the token, so redact it).
You can find my mail in the license description [here](https://github.com/bropat/ioBroker.eufy-security/blob/master/LICENSE).

**Comment by pldmgg** [comment]
Hi @bropat - I can't quite figure out how to enable "debug mode 2" for the eufy adapter. I looked through the Admin UI and couldn't really find anything. I also found iobroker.json, but I'm sure that's not what you're looking for. The other documentation refers to using Webstorm - Is Webstorm officially how I'm supposed to enable debug mode 2 for a particular adapter?

**Comment by bropat** [comment]
@pldmgg Sorry, when copying the message I lost the link ;). Look [here](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug)

**Comment by Radushka** [comment]
Thanks for all your hard work @bropat!

Unfortunately, same here. It looks like the stream is processed ok in the log. But it can not be accessed at [http://<IPAddress>:8082/eufy-security.0/T8010XXXXXXXXXXX/live/T811XXXXXXXXXXXX.m3u8](http://<IPAddress>:8082/eufy-security.0/T8010XXXXXXXXXXX/live/T811XXXXXXXXXXXX.m3u8). Same goes for [http://<IPAddress>:8082/eufy-security.0/T8010XXXXXXXXXXX/last_live/T811XXXXXXXXXXXX.jpeg](http://<IPAddress>:8082/eufy-security.0/T8010XXXXXXXXXXX/last_live/T811XXXXXXXXXXXX.jpeg). I get a File T8010XXXXXXXXXXX/last_live/T811XXXXXXXXXXXX.m3u8 not found: Not exists

**Comment by pldmgg** [comment]
Just tried version 0.2.2 and this is resolved. Thanks so much for your work on this!

**Comment by rmickael62** [comment]
Hi @bropat
Version 0.2.2 / Eufy Cam 2
I have deleted the instance ioBroker.eufy-security and create a new one.
http://192.168.1.135:8082/eufy-security.0/T8010XXXXXXXXXXX/live/T8114XXXXXXXXXXX.m3u8 => empty after activation of the flow.
attached log file (DEBUG)
Thank you great work!
[iobroker.2021-02-16.log](https://github.com/bropat/ioBroker.eufy-security/files/5989525/iobroker.2021-02-16.log)
