### ISSUE TITLE
EufyCam 2 Pro (2k Modell) wird nicht angezeigt

### ISSUE THREAD

**Issue by thogens** [bropat/ioBroker.eufy-security#8]
Hallo,

ich besitze neben zahlreicher anderer Eufys auch eine 2 Pro (2k Modell).
Dieses wird jedoch unter den Objekte nicht aufgeführt.

Grüße,
Thomas

**Comment by bropat** [comment]
Hallo,

sollte mit der letzten Release (0.0.2) behoben sein.

Grüße
Patrick

**Comment by thogens** [comment]
Hi!

Sorry der Nachfrage. Ich glaube ich bin zu blöd, den Adapter upzudaten.
Wie kriege ich das hin? Im ioBroker selbst wird mit die Version nicht angezeigt. 
Danke für die Hilfe!
