### ISSUE TITLE
Livestream of doorbell video is scrambled

### ISSUE THREAD

**Issue by cratoo** [bropat/ioBroker.eufy-security#83]
If you start a live stream of the doorbell by clicking the state in iobroker.admin you get the relative url and if you start this in vlc, half of the picture is scrambled in a typical "broken stream" way.

**Comment by cratoo** [comment]
As you mentioned a race condition fix in 0.2.5 for broken live streams. I just tried it, but it did not help.

**Comment by bropat** [comment]
@cratoo Try version 0.3.0 and let me know.
This version no longer encodes the video, it just muxes to HLS. Audio and video data remain untouched.

**Comment by cratoo** [comment]
Hmm this does not work at all anymore. After the stream finishes, there is a .ts file in the last_live folder which is way too small  (180kb). Will need to do "silly" debugging log again. Possibly tonight, but can't promise.

**Comment by bropat** [comment]
@cratoo i have released version 0.3.1 which fixes a regression... ;)

**Comment by cratoo** [comment]
Great job, looks awesome now! And the response until the stream is available is also so much better :)
