### ISSUE TITLE
Feature Request - A Way To Pick Up Livestream Url When Eufy Cameras Record Motion?

### ISSUE THREAD

**Issue by pldmgg** [bropat/ioBroker.eufy-security#84]
Not sure if this is possible given Eufy's backend, but would it be possible to automatically populate the livestream url value whenever a camera starts recording due to motion?

**Comment by bropat** [comment]
Everybody can solve this need by himself by installing and using e.g. the [Javascript Adapter](https://github.com/ioBroker/ioBroker.javascript) in the ioBroker. Thereby you can solve it with [blockly](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/blockly.md) or also with your own Javascript/Typescript script. Just react on the change of the state "motion_detected" and start the livestream with the button state "start_stream".

**Comment by pldmgg** [comment]
Awesome! Thanks for the advice!
