### ISSUE TITLE
"live" directory always empty, no m3u8 file

### ISSUE THREAD

**Issue by rmickael62** [bropat/ioBroker.eufy-security#85]
**Describe the bug**  
After activation of the start stream button "live" directory always empty, no m3u8 file 

**To Reproduce**  
1. Go to 'Objets'
2. Click on 'eufy-security.0.T8010XXXXXXXXXXX.cameras.T8114XXXXXXXXXXX.start_stream' button.start

**Expected behavior**  
The presence of the eufy-security.0/T8010XXXXXXXXXXX/live/T8114XXXXXXXXXXX.m3u8 file. 

**Screenshots & Logfiles**  
attached logfiles
[LogEufy18022021.txt](https://github.com/bropat/ioBroker.eufy-security/files/6004315/LogEufy18022021.txt)

**Versions:**  
 - Adapter version: 0.2.3
 - JS-Controller version: 3.1.6
 - Node version: v14.15.3
 - Operating system: Ubuntu 20.04.1 LTS

**Comment by bropat** [comment]
Hi @rmickael62 ,

can you please increase the debug mode to silly, reproduce the issue and send me the logs? With silly debug mode I get more information to understand the problem.

Thanks!

**Comment by rmickael62** [comment]
Hi @bropat,

Thank you for the interest of my problem, here is the requested file.
[LogEufy20022021.txt](https://github.com/bropat/ioBroker.eufy-security/files/6015258/LogEufy20022021.txt)

**Comment by bropat** [comment]
@rmickael62 try version 0.2.5 and let me know.

**Comment by rmickael62** [comment]
log with version 0.2.5.
I delete the instance and put a new one and leave the stream for a few seconds for a rather small log.
still no m3u8 file created  :-(
[LogEufy20022021_2.txt](https://github.com/bropat/ioBroker.eufy-security/files/6016807/LogEufy20022021_2.txt)

**Comment by bropat** [comment]
@rmickael62 can you try version 0.3.0 and let me know?

**Comment by rmickael62** [comment]
I don't think I'm lucky because the problem always seems the same.
[LogEufy07032021.txt](https://github.com/bropat/ioBroker.eufy-security/files/6097586/LogEufy07032021.txt)

**Comment by ronaldt80** [comment]
@rmickael62 - i had the same issue. In the end I reinstalled everything (including iobroker). I run iobroker just for eufy so not a big deal for me. Not sure what your setup is but to replicate my solution (and rule out other issues) perhaps initiate a new docker container and test with just a webserver and eufy adapter installed?

**Comment by rmickael62** [comment]
@ronaldt80 I had a glimmer of hope when I saw your massage because I did not try to reinstall iobroker in full but unfortunately after creating a new iobroker instance under docker the problem is still present.

**Comment by bropat** [comment]
@rmickael62 
I think the best solution is to organize a google meet and troubleshoot the problem right at your end.

Let me know.

**Comment by rmickael62** [comment]
@bropat It's a good idea but I only master oral French
