### ISSUE TITLE
Problème avec Jeedom

### ISSUE THREAD

**Issue by Matthieu-mi** [bropat/ioBroker.eufy-security#87]
Bonjour,
J'ai installer sur mon raspberry Jeedom et Apache 3.8.3
J'ai ensuite installer eufy va ligne de commande et créé les commande python pour actionner les changements d'états mais j'ai ce retour

Erreur sur /var/www/html/plugins/script/data/maison.sh 2>&1 valeur retournée : 1. Détails : Traceback (most recent call last): File « /home/jeedom/Eufy/Maison.PY », line 8, in from eufy_security.types import GuardMode ModuleNotFoundError: No module named ‹ eufy_security.types ›

Je ne sais pas quoi faire, si une âme charitable veux bien m'aider...

Merci d’avoir pris le temps de me lire et de vos retour
Cordialement
Matthieu

**Comment by bropat** [comment]
Hi @Matthieu-mi,
I don't know French, but I'll try to answer anyway with the help of a translation software (if possible please write in English!).

This adapter is only for ioBroker and is not compatible with any other home automation software. 
If an integration with another home automation software should take place, then I suggest to use [this library](https://github.com/bropat/eufy-security-client).
