### ISSUE TITLE
Installation of eufy-security is unclear to newcomers

### ISSUE THREAD

**Issue by sunsear** [bropat/ioBroker.eufy-security#93]
I could not find how to install Dufy-security at first.

**Comment by sunsear** [comment]
I've created a Pull Request to implement some docs for installation:

https://github.com/bropat/ioBroker.eufy-security/pull/92

**Comment by t0m5k1** [comment]
I don't even know how to start or access the gui I see screenshots of!
Installed it but totally lost as to what to do next.

**Comment by scottmil** [comment]
I second all of the above comments regarding a request for installation/build instructions.  I am new to node.js and npm, and I am unclear how to install this very useful code.
