### ISSUE TITLE
uncaught exception after stop_stream in .T8020 (Battery doorbell 1080p)

### ISSUE THREAD

**Issue by PabloVal-coder** [bropat/ioBroker.eufy-security#98]
**Describe the bug**  
A clear and concise description of what the bug is:
When I try to stop stream, I get:
uncaught exception: ffmpeg exited with code 255
And then:
instance system.adapter.eufy-security.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

After it, I need to manual restart instance to be able to stream again.

**To Reproduce**  
1.- I click on start_stream.
2.- I can access to live stream.
3.- I click on stop_stream.
4.- Log error in silly mode:

`
host.bee74d33d7fb | 2021-03-16 08:42:14.203 | info | Restart adapter system.adapter.eufy-security.0 because enabled
-- | -- | -- | --
host.bee74d33d7fb | 2021-03-16 08:42:14.201 | error | instance system.adapter.eufy-security.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
eufy-security.0 | 2021-03-16 08:42:13.744 | info | (27671) Disconnected from station T8020P1020341B19.
eufy-security.0 | 2021-03-16 08:42:13.675 | debug | (27671) P2PClientProtocol.onClose():
eufy-security.0 | 2021-03-16 08:42:13.675 | warn | (27671) Terminated (UNCAUGHT_EXCEPTION): Without reason
eufy-security.0 | 2021-03-16 08:42:13.675 | info | (27671) terminating
eufy-security.0 | 2021-03-16 08:42:13.675 | info | (27671) Disconnect from station T8020P1020341B19.
eufy-security.0 | 2021-03-16 08:42:13.672 | silly | (27671) States system redis pmessage io.messagebox.system.adapter.eufy-security.0/io.messagebox.system.adapter.eufy-security.0:{"command":"addNotification","message":{"result":"ok"},"from":"system.hos
eufy-security.0 | 2021-03-16 08:42:13.668 | error | (27671) ffmpeg exited with code 255: frame= 103 fps=9.8 q=-1.0 Lsize=N/A time=00:00:13.19 bitrate=N/A speed=1.25x video:959kB audio:35kB subtitle:0kB other streams:0kB global headers:0kB muxing o
eufy-security.0 | 2021-03-16 08:42:13.668 | error | (27671) Error: ffmpeg exited with code 255: frame= 103 fps=9.8 q=-1.0 Lsize=N/A time=00:00:13.19 bitrate=N/A speed=1.25x video:959kB audio:35kB subtitle:0kB other streams:0kB global headers:0kB m
eufy-security.0 | 2021-03-16 08:42:13.667 | error | (27671) uncaught exception: ffmpeg exited with code 255: frame= 103 fps=9.8 q=-1.0 Lsize=N/A time=00:00:13.19 bitrate=N/A speed=1.25x video:959kB audio:35kB subtitle:0kB other streams:0kB global
eufy-security.0 | 2021-03-16 08:42:12.690 | debug | (27671) state eufy-security.0.T8020P1020341B19.cameras.T8222P002034304E.livestream deleted
eufy-security.0 | 2021-03-16 08:42:12.689 | silly | (27671) States user redis pmessage eufy-security.0.T8020P1020---B--.*/eufy-security.0.T8020P1020341B19.cameras.T8222P0020---B--.livestream:null
eufy-security.0 | 2021-03-16 08:42:12.677 | silly | (27671) onStopLivestream(): station: T8020P1020---B-- device: T8222P002034304E
eufy-security.0 | 2021-03-16 08:42:12.675 | info | (27671) Livestream of camera T8222P0020---B-- stopped.
eufy-security.0 | 2021-03-16 08:42:12.674 | debug | (27671) BatteryDoorbellCamera.stopStream(): Response: {"code":0,"msg":"Succeed."}

`

**Expected behavior**  
I understand what should happen is the stream stops and, if there is an error in ffmpeg, should not impact the instance in an uncaught exception.

After that, if no manual restart is done, its not possible to start_stream again before doing a manual restart of the instance.

**Versions:**  
 - Adapter version: 0.4.2
 - JS-Controller version: dont know.
 - Node version: v12.21.0
 - Operating system: Debian

**Comment by PabloVal-coder** [comment]
Hi, if you need any help from my side, I can try to help you :)

**Comment by bropat** [comment]
Hi @PabloVal-coder,

thank you, I will let you know.

**Comment by bropat** [comment]
Registering SIGINT handler to cleanly exit application doesn't work because ffmpeg gets killed right away #644

**Comment by bropat** [comment]
I found the following closed issue for the lib I am using:

https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/644#

 Will check and implement the solution. I will let you know.

**Comment by PabloVal-coder** [comment]
Thats great 👍

**Comment by bropat** [comment]
@PabloVal-coder Please try version 0.6.0 and let me know.
